const bpData = [
            // Satipatthana (4) — sky — all = sati applied to 4 domains
            { id: 1, key: 'kayanupassana', pali: 'Kāyānupassanā-satipaṭṭhāna', name: 'ကာယာနုပဿနာ', group: 'satipatthana', dhamma: 'sati', icon: 'fa-person',
              desc: 'ကိုယ်ခန္ဓာ (အသက်ရှူသွင်း/ထုတ်၊ ရုပ်၏ ဣရိယာပုတ်) ကို အနိစ္စ/ဒုက္ခ/အနတ္တ အဖြစ် သတိထား ကပ်၍ ရှုမှတ်ခြင်း — သတိစေတသိက်ကို ကိုယ်ခန္ဓာအပေါ် အသုံးချခြင်း။',
              example: 'အသက်ရှူဝင်/ထွက်ကို စိတ်ချမှတ်ကြည့်ခြင်း (အာနာပါနဿတိ)။' },
            { id: 2, key: 'vedananupassana', pali: 'Vedanānupassanā-satipaṭṭhāna', name: 'ဝေဒနာနုပဿနာ', group: 'satipatthana', dhamma: 'sati', icon: 'fa-heart-pulse',
              desc: 'ခံစားမှု (သုခ/ဒုက္ခ/ဥပေက္ခာ) ကို အနိစ္စ/ဒုက္ခ/အနတ္တ အဖြစ် သတိထား ကပ်၍ ရှုမှတ်ခြင်း။',
              example: 'ခန္ဓာကိုယ် နာကျင်ချိန်၌ "နာကျင်မှု ဖြစ်ပေါ်နေသည်" ဟု ခံစားချက်ကိုသာ ကပ်၍ ရှုမှတ်ခြင်း (ဒေါသ မထည့်ဘဲ)။' },
            { id: 3, key: 'cittanupassana', pali: 'Cittānupassanā-satipaṭṭhāna', name: 'စိတ္တာနုပဿနာ', group: 'satipatthana', dhamma: 'sati', icon: 'fa-brain',
              desc: 'စိတ်၏ အခြေအနေ (ရာဂနှင့်ယှဉ်/မယှဉ်၊ ဒေါသနှင့်ယှဉ်/မယှဉ် စသည်) ကို သတိထား ကပ်၍ ရှုမှတ်ခြင်း။',
              example: '"ယခု စိတ်ထဲ လောဘ ဖြစ်နေသည်" ဟု စိတ်၏ အခြေအနေကို ရိပ်စား မိစွာ သတိထားနိုင်ခြင်း။' },
            { id: 4, key: 'dhammanupassana', pali: 'Dhammānupassanā-satipaṭṭhāna', name: 'ဓမ္မာနုပဿနာ', group: 'satipatthana', dhamma: 'sati', icon: 'fa-scroll',
              desc: 'နီဝရဏ၊ ခန္ဓာ၊ အာယတန၊ ဗောဇ္ဈင်၊ သစ္စာ စသော တရားအစုအမျိုးမျိုးကို သတိထား ကပ်၍ ရှုမှတ်ခြင်း။',
              example: 'ခန္ဓာငါးပါး ဖြစ်ပျက်ပုံကို "ဤသည် ရုပ်၊ ဤသည် ဝေဒနာ၊ ဤသည် သညာ၊ ဤသည် သင်္ခါရ၊ ဤသည် ဝိညာဏ်" ဟု တရားအမျိုးအစားအလိုက် ခွဲခြား ရှုမှတ်ခြင်း။' },

            // Sammappadhana (4) — emerald — all = viriya applied 4 ways
            { id: 5, key: 'samvarappadhana', pali: 'Saṃvarappadhāna', name: 'သံဝရပ္ပဓာန်', group: 'sammappadhana', dhamma: 'viriya', icon: 'fa-shield',
              desc: 'မဖြစ်ပေါ်သေးသော အကုသိုလ်ကို မဖြစ်ပေါ်စေရန် တားဆီး ကာကွယ်သော အားထုတ်မှု — ဣန္ဒြေသံဝရ (ဣန္ဒြေထိန်းသိမ်းခြင်း) အားထုတ်မှု ဖြစ်သည်။',
              example: 'မျက်စိဖြင့် နှစ်သက်ဖွယ်ကို မြင်ရသောအခါ၊ လောဘ မဖြစ်ပေါ်အောင် သတိဖြင့် ထိန်းချုပ်ခြင်း။' },
            { id: 6, key: 'pahanappadhana', pali: 'Pahānappadhāna', name: 'ပဟာနပ္ပဓာန်', group: 'sammappadhana', dhamma: 'viriya', icon: 'fa-trash',
              desc: 'ဖြစ်ပေါ်ပြီးသား အကုသိုလ်ကို ပယ်ဖျက်ရန် အားထုတ်မှု။',
              example: 'ဒေါသ ဖြစ်ပေါ်လာသည်နှင့်တစ်ပြိုင်နက် ချက်ချင်း သတိဖြင့် ရိပ်စား၍ ပယ်ဖျောက်ရန် ကြိုးပမ်းခြင်း။' },
            { id: 7, key: 'bhavanappadhana', pali: 'Bhāvanāppadhāna', name: 'ဘာဝနာပ္ပဓာန်', group: 'sammappadhana', dhamma: 'viriya', icon: 'fa-spa',
              desc: 'မဖြစ်ပေါ်သေးသော ကုသိုလ်ကို ဖြစ်ပေါ်စေရန် ပွားများ အားထုတ်မှု။',
              example: 'ယခင်က တစ်ခါမျှ မလေ့ကျင့်ဖူးသေးသော ဘာဝနာအမျိုးအစားကို အသစ် စတင် လေ့ကျင့်ခြင်း။' },
            { id: 8, key: 'anurakkhanappadhana', pali: 'Anurakkhaṇappadhāna', name: 'အနုရက္ခဏပ္ပဓာန်', group: 'sammappadhana', dhamma: 'viriya', icon: 'fa-hands-holding-circle',
              desc: 'ဖြစ်ပေါ်ပြီးသား ကုသိုလ်ကို ဆက်လက် တိုးတက်စေရန် ထိန်းသိမ်း အားထုတ်မှု။',
              example: 'ရရှိပြီးသား သမာဓိအခြေအနေကို မပျောက်စေရန် ဆက်လက် ပြုစုပျိုးထောင်ခြင်း။' },

            // Iddhipada (4) — cyan — 4 different dhammas
            { id: 9, key: 'chandiddhipada', pali: 'Chandiddhipāda', name: 'ဆန္ဒိဒ္ဓိပါဒ်', group: 'iddhipada', dhamma: 'chanda', icon: 'fa-hand-sparkles',
              desc: 'ပြုလုပ်လိုသော ဆန္ဒ (လိုလားမှု) ကို အောင်မြင်မှု၏ အခြေခံ အုတ်မြစ်အဖြစ် အသုံးချခြင်း။',
              example: 'တရားထိုင်လိုသော စိတ်ဆန္ဒ ပြင်းထန်စွာ ရှိခြင်းက ဘာဝနာ တိုးတက်ရန် အခြေခံ ဖြစ်သည်။' },
            { id: 10, key: 'viriyiddhipada', pali: 'Viriyiddhipāda', name: 'ဝီရိယိဒ္ဓိပါဒ်', group: 'iddhipada', dhamma: 'viriya', icon: 'fa-fire-flame-curved',
              desc: 'ကြိုးစားအားထုတ်မှု (ဝီရိယ) ကို အောင်မြင်မှု၏ အခြေခံ အုတ်မြစ်အဖြစ် အသုံးချခြင်း။',
              example: 'အနှောင့်အယှက်များ ကြားမှပင် စိုက်ကြံ့ ကြိုးစားနေခြင်း။' },
            { id: 11, key: 'cittiddhipada', pali: 'Cittiddhipāda', name: 'စိတ္တိဒ္ဓိပါဒ်', group: 'iddhipada', dhamma: 'citta', icon: 'fa-brain',
              desc: 'စိတ်ကို တစ်စိတ်တည်း စူးစိုက်ထားနိုင်မှု ကိုယ်တိုင်ကို အောင်မြင်မှု၏ အခြေခံ အုတ်မြစ်အဖြစ် အသုံးချခြင်း။',
              example: 'အာရုံတစ်ခုတည်းအပေါ် စိတ်ကို အပြည့်အဝ စွဲမြဲစွာ ထားနိုင်ခြင်း။' },
            { id: 12, key: 'vimamsiddhipada', pali: 'Vīmaṃsiddhipāda', name: 'ဝီမံသိဒ္ဓိပါဒ်', group: 'iddhipada', dhamma: 'panna', icon: 'fa-magnifying-glass',
              desc: 'စူးစမ်းဆင်ခြင် သုံးသပ်တတ်သော ပညာကို အောင်မြင်မှု၏ အခြေခံ အုတ်မြစ်အဖြစ် အသုံးချခြင်း။',
              example: 'ဘယ်နည်းလမ်းက ပိုအဆင်ပြေသည်ကို ပညာဖြင့် ဆင်ခြင် ရွေးချယ်ခြင်း။' },

            // Indriya (5) — violet
            { id: 13, key: 'saddhindriya', pali: 'Saddhindriya', name: 'သဒ္ဓိန္ဒြေ', group: 'indriya', dhamma: 'saddha', icon: 'fa-hands-praying',
              desc: 'ယုံကြည်မှု (သဒ္ဓါ) သည် ယုံကြည်မှု လုံးဝ ကင်းမဲ့ခြင်းကို လွှမ်းမိုး အုပ်ချုပ်ခြင်း။',
              example: 'ရတနာသုံးပါးကို တည်ကြည်စွာ ယုံကြည်ခြင်းက ဘာဝနာ ဆက်လက် အားထုတ်ရန် တွန်းအား ဖြစ်လာသည်။' },
            { id: 14, key: 'viriyindriya', pali: 'Viriyindriya', name: 'ဝီရိယိန္ဒြေ', group: 'indriya', dhamma: 'viriya', icon: 'fa-bolt',
              desc: 'ကြိုးစားအားထုတ်မှု (ဝီရိယ) သည် ပျင်းရိမှုကို လွှမ်းမိုး အုပ်ချုပ်ခြင်း။',
              example: 'ပင်ပန်းသော်လည်း အားထုတ်မှုကို မရပ်ဘဲ ဆက်လက် ကြိုးပမ်းနိုင်ခြင်း။' },
            { id: 15, key: 'satindriya', pali: 'Satindriya', name: 'သတိန္ဒြေ', group: 'indriya', dhamma: 'sati', icon: 'fa-eye',
              desc: 'သတိသည် ပေါ့ဆမှု (မှေ့ာမေ့ခြင်း) ကို လွှမ်းမိုး အုပ်ချုပ်ခြင်း။',
              example: 'ပစ္စုပ္ပန် အာရုံကို မပျောက်စေဘဲ အမြဲ သတိနှင့် ကပ်၍ ရှိနေနိုင်ခြင်း။' },
            { id: 16, key: 'samadhindriya', pali: 'Samādhindriya', name: 'သမာဓိန္ဒြေ', group: 'indriya', dhamma: 'samadhi', icon: 'fa-crosshairs',
              desc: 'စိတ်တည်ငြိမ်မှု (သမာဓိ) သည် စိတ်ပျံ့လွင့်မှု (ဥဒ္ဓစ္စ) ကို လွှမ်းမိုး အုပ်ချုပ်ခြင်း။',
              example: 'အာရုံမှ စိတ်မလွှင့်စေဘဲ တည်ငြိမ်စွာ ထိန်းထားနိုင်ခြင်း။' },
            { id: 17, key: 'pannindriya_bp', pali: 'Paññindriya', name: 'ပညိန္ဒြေ', group: 'indriya', dhamma: 'panna', icon: 'fa-lightbulb',
              desc: 'ပညာသည် အသိဉာဏ် ကင်းမဲ့ခြင်း (အဝိဇ္ဇာ) ကို လွှမ်းမိုး အုပ်ချုပ်ခြင်း။',
              example: 'ခန္ဓာငါးပါး၏ အနိစ္စ/ဒုက္ခ/အနတ္တ သဘောကို ပညာဖြင့် ထိုးထွင်း သိမြင်နိုင်ခြင်း။' },

            // Bala (5) — rose — same 5 dhammas as indriya, but "unshakeable" framing
            { id: 18, key: 'saddhabala', pali: 'Saddhābala', name: 'သဒ္ဓါဗလ', group: 'bala', dhamma: 'saddha', icon: 'fa-shield-heart',
              desc: 'ယုံကြည်မှုသည် မယုံကြည်မှုတို့၏ တုန်လှုပ်ခြင်း မခံစေနိုင်အောင် ခိုင်မြဲသော အားအင် ဖြစ်လာခြင်း (ဣန္ဒြေထက် တစ်ဆင့် ပိုမို ခိုင်မာ)။',
              example: 'အယူမှား ဆွဲဆောင်မှုများ ကြားမှပင် သဒ္ဓါတရား မတုန်လှုပ်တော့ခြင်း။' },
            { id: 19, key: 'viriyabala', pali: 'Viriyabala', name: 'ဝီရိယဗလ', group: 'bala', dhamma: 'viriya', icon: 'fa-dumbbell',
              desc: 'ကြိုးစားအားထုတ်မှုသည် ပျင်းရိမှု၏ တွန်းလှန်ခြင်း မခံစေနိုင်အောင် ခိုင်မြဲလာခြင်း။',
              example: 'မည်မျှ ပင်ပန်းစေကာမူ အားထုတ်မှု လုံးဝ မတုန်လှုပ်တော့ခြင်း။' },
            { id: 20, key: 'satibala', pali: 'Satibala', name: 'သတိဗလ', group: 'bala', dhamma: 'sati', icon: 'fa-anchor',
              desc: 'သတိသည် ပေါ့ဆမှု၏ တွန်းလှန်ခြင်း မခံစေနိုင်အောင် ခိုင်မြဲလာခြင်း။',
              example: 'မည်သည့် အခြေအနေမျှ သတိ လုံးဝ မပျောက်တော့ခြင်း။' },
            { id: 21, key: 'samadhibala', pali: 'Samādhibala', name: 'သမာဓိဗလ', group: 'bala', dhamma: 'samadhi', icon: 'fa-mountain',
              desc: 'စိတ်တည်ငြိမ်မှုသည် စိတ်ပျံ့လွင့်မှု၏ တွန်းလှန်ခြင်း မခံစေနိုင်အောင် ခိုင်မြဲလာခြင်း။',
              example: 'ပြင်ပ အသံဆူညံမှုများ ကြားမှပင် စိတ်တည်ငြိမ်မှု မပျက်စီးတော့ခြင်း။' },
            { id: 22, key: 'pannabala', pali: 'Paññābala', name: 'ပညာဗလ', group: 'bala', dhamma: 'panna', icon: 'fa-brain',
              desc: 'ပညာသည် အသိဉာဏ် ကင်းမဲ့ခြင်း၏ တွန်းလှန်ခြင်း မခံစေနိုင်အောင် ခိုင်မြဲလာခြင်း။',
              example: 'အလွဲအမှား ဆွဲဆောင်ချက်များကို ပညာဖြင့် ချက်ချင်း ခွဲခြား သိမြင်နိုင်ခြင်း။' },

            // Bojjhanga (7) — amber
            { id: 23, key: 'satisambojjhanga', pali: 'Satisambojjhaṅga', name: 'သတိသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'sati', icon: 'fa-eye',
              desc: 'ဗောဇ္ဈင် (၇) ပါးအနက် ပထမဆုံး — ကျန် (၆) ပါးလုံးကို ထိန်းညှိပေးသော သတိတရား။',
              example: 'ဘာဝနာအခြေအနေကို အချိန်တိုင်း သတိထား ကြည့်ရှုနေနိုင်ခြင်း။' },
            { id: 24, key: 'dhammavicayasambojjhanga', pali: 'Dhammavicayasambojjhaṅga', name: 'ဓမ္မဝိစယသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'panna', icon: 'fa-magnifying-glass-chart',
              desc: 'တရားများကို ပညာဖြင့် စိစစ် ခွဲခြမ်းသိမြင်ခြင်း။',
              example: 'ဖြစ်ပေါ်နေသော ခံစားမှု၏ အနိစ္စသဘောကို ပညာဖြင့် ထိုးထွင်း စိစစ်ခြင်း။' },
            { id: 25, key: 'viriyasambojjhanga', pali: 'Viriyasambojjhaṅga', name: 'ဝီရိယသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'viriya', icon: 'fa-fire',
              desc: 'ဘာဝနာ တိုးတက်ရန် ကြိုးစားအားထုတ်မှု။',
              example: 'ပျင်းရိစိတ် ဖြစ်ပေါ်လာသောအခါ ပြန်လည် အားစိုက် ကြိုးစားခြင်း။' },
            { id: 26, key: 'pitisambojjhanga', pali: 'Pītisambojjhaṅga', name: 'ပီတိသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'piti', icon: 'fa-face-smile-beam',
              desc: 'ဘာဝနာ တိုးတက်လာသည်နှင့်အမျှ ဖြစ်ပေါ်လာသော နှစ်သက် ရွှင်လန်းမှု။',
              example: 'တရားထိုင်ရင်း ကိုယ်တစ်ခုလုံး ချမ်းမြေ့ ရွှင်လန်းသည့် ခံစားမှု ဖြစ်ပေါ်လာခြင်း။' },
            { id: 27, key: 'passaddhisambojjhanga', pali: 'Passaddhisambojjhaṅga', name: 'ပဿဒ္ဓိသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'passaddhi', icon: 'fa-water',
              desc: 'စိတ်နှင့် စေတသိက်တို့ ငြိမ်းအေးသက်သာမှု။',
              example: 'ပီတိ ရှင်းသွားပြီးနောက် စိတ် ပို၍ တည်ငြိမ် အေးချမ်းလာခြင်း။' },
            { id: 28, key: 'samadhisambojjhanga', pali: 'Samādhisambojjhaṅga', name: 'သမာဓိသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'samadhi', icon: 'fa-crosshairs',
              desc: 'အာရုံတစ်ခုတည်းအပေါ် စိတ် တည်ငြိမ်စွာ စူးစိုက်နိုင်မှု။',
              example: 'ပဿဒ္ဓိ ဖြစ်ပေါ်ပြီးနောက် စိတ် ပို၍ နက်နက်ရှိုင်းရှိုင်း တည်ငြိမ်လာခြင်း။' },
            { id: 29, key: 'upekkhasambojjhanga', pali: 'Upekkhāsambojjhaṅga', name: 'ဥပေက္ခာသမ္ဗောဇ္ဈင်', group: 'bojjhanga', dhamma: 'upekkha', icon: 'fa-scale-balanced',
              desc: 'ကျန် (၆) ပါးလုံး မျှတစွာ အလုပ်လုပ်နေအောင် လျစ်လျူမြင် ထိန်ညှိပေးမှု (တတြမဇ္ဈတ္တတာ)။',
              example: 'ဝီရိယနှင့် သမာဓိ မျှတစွာ ညီမျှနေအောင် ထိန်းညှိပေးနိုင်ခြင်း — အားလွန်လျှင် ပီတိဘက်သို့၊ အားနည်းလျှင် ပျင်းရိဘက်သို့ မသွားစေခြင်း။' },

            // Magganga (8) — indigo
            { id: 30, key: 'sammaditthi', pali: 'Sammādiṭṭhi', name: 'သမ္မာဒိဋ္ဌိ', group: 'magganga', dhamma: 'panna', icon: 'fa-eye',
              desc: 'သစ္စာလေးပါးကို မှန်ကန်စွာ သိမြင်သော ပညာ — မဂ်ဂင် (၈) ပါးအနက် ဦးဆောင်။',
              example: 'ဒုက္ခ၊ ဒုက္ခ၏ အကြောင်း၊ ဒုက္ခ ချုပ်ငြိမ်းရာ၊ ချုပ်ငြိမ်းရာသို့ ဦးတည်သည့် လမ်းစဉ် — ဤ (၄) ချက်ကို မှန်ကန်စွာ သိမြင်ခြင်း။' },
            { id: 31, key: 'sammasankappa', pali: 'Sammāsaṅkappa', name: 'သမ္မာသင်္ကပ္ပ', group: 'magganga', dhamma: 'vitakka', icon: 'fa-compass',
              desc: 'မှန်ကန်သော အကြံအစည် — နေက္ခမ္မသင်္ကပ္ပ (တဏှာမှ ကင်းဝေးလိုမှု)၊ အဗျာပါဒသင်္ကပ္ပ (မုန်းတီးမှု ကင်းသော အကြံ)၊ အဝိဟိංသာသင်္ကပ္ပ (နှိပ်စက်မှု ကင်းသော အကြံ)။',
              example: 'သူတစ်ပါးအပေါ် ကြင်နာစိတ်ဖြင့် စဉ်းစားခြင်း၊ တပ်မက်မှု ကင်းသော ဘဝကို ရည်ရွယ် အကြံပြုခြင်း။' },
            { id: 32, key: 'sammavaca', pali: 'Sammāvācā', name: 'သမ္မာဝါစာ', group: 'magganga', dhamma: 'virati', icon: 'fa-comment',
              desc: 'မှန်ကန်သော စကားပြောဆိုမှု — မုသား၊ ကုန်းချော၊ ကြမ်းတမ်း၊ အချည်းနှီး စကားများမှ ကြဉ်ရှောင်ခြင်း (ဝိရတီစေတသိက်)။',
              example: 'အမှန်တရားကိုသာ ပြောဆိုခြင်း၊ ကွဲပြားအောင် မကုန်းချော ပြောဆိုခြင်း။' },
            { id: 33, key: 'sammakammanta', pali: 'Sammākammanta', name: 'သမ္မာကမ္မန္တ', group: 'magganga', dhamma: 'virati', icon: 'fa-hand',
              desc: 'မှန်ကန်သော ကိုယ်ကျင့်တရား — အသက်သတ်ခြင်း၊ ခိုးဝှက်ခြင်း၊ ကာမေသုမိစ္ဆာစာရ ကျင့်ခြင်းမှ ကြဉ်ရှောင်ခြင်း (ဝိရတီစေတသိက်)။',
              example: 'အသက်ရှင်သတ္တဝါများကို မညှဉ်းပန်းခြင်း၊ သူတစ်ပါး ပိုင်ဆိုင်မှုကို မခိုးယူခြင်း။' },
            { id: 34, key: 'sammaajiva', pali: 'Sammāājīva', name: 'သမ္မာအာဇီဝ', group: 'magganga', dhamma: 'virati', icon: 'fa-briefcase',
              desc: 'မှန်ကန်သော အသက်မွေးမှု — မှားယွင်းသော စကား၊ ကိုယ်အမူအရာဖြင့် အသက်မွေးခြင်းမှ ကြဉ်ရှောင်ခြင်း (ဝိရတီစေတသိက်)။',
              example: 'သူတစ်ပါးကို အန္တရာယ်ပြုသော လက်နက်၊ အဆိပ်၊ အသားရောင်းဝယ်မှု စသည်တို့မှ ကြဉ်ရှောင်၍ အသက်မွေးခြင်း။' },
            { id: 35, key: 'sammavayama', pali: 'Sammāvāyāma', name: 'သမ္မာဝါယာမ', group: 'magganga', dhamma: 'viriya', icon: 'fa-person-running',
              desc: 'မှန်ကန်သော အားထုတ်မှု — သမ္မပ္ပဓာန် (၄) ပါးနှင့် အနက်တူ။',
              example: 'အထက်တွင် ဖော်ပြခဲ့သော သံဝရ/ပဟာန/ဘာဝနာ/အနုရက္ခဏ ပ္ပဓာန် (၄) မျိုး။' },
            { id: 36, key: 'sammasati', pali: 'Sammāsati', name: 'သမ္မာသတိ', group: 'magganga', dhamma: 'sati', icon: 'fa-anchor',
              desc: 'မှန်ကန်သော သတိ — သတိပဋ္ဌာန် (၄) ပါးနှင့် အနက်တူ။',
              example: 'အထက်တွင် ဖော်ပြခဲ့သော ကာယာ/ဝေဒနာ/စိတ္တာ/ဓမ္မာနုပဿနာ (၄) မျိုး။' },
            { id: 37, key: 'sammasamadhi', pali: 'Sammāsamādhi', name: 'သမ္မာသမာဓိ', group: 'magganga', dhamma: 'samadhi', icon: 'fa-crosshairs',
              desc: 'မှန်ကန်သော စိတ်တည်ငြိမ်မှု — ဈာန် (၄) ပါး (သို့) (၅) ပါးအထိ တိုးတက်နိုင်သော ဧကဂ္ဂတာသဘော။',
              example: 'အာရုံတစ်ခုတည်းအပေါ် ပျံ့လွင့်မှု ကင်းစင်စွာ တည်ငြိမ် စူးစိုက်နိုင်ခြင်း — ဈာန်အထိ ဖွံ့ဖြိုးနိုင်သည်။' }
        ];

