const bhumiData = [
            // Kamabhumi (11) — rose
            { id: 1, key: 'niraya', pali: 'Niraya', name: 'ငရဲဘုံ', group: 'kamabhumi', icon: 'fa-fire', desc: 'အပါယ်ဘုံ (၄) ပါးအနက် ဆင်းရဲဒုက္ခ အပြင်းထန်ဆုံး ဘုံ — အကုသိုလ်ကံ၏ အကျိုးဆက်ဖြင့် ပဋိသန္ဓေယူရသည်။', example: 'သတ္တဝါတို့ အလွန်ပြင်းထန်သော ဝေဒနာများကို ဆက်တိုက် ခံစားနေရသော ဘုံ။' },
            { id: 2, key: 'tiracchana', pali: 'Tiracchāna-yoni', name: 'တိရစ္ဆာန်ဘုံ', group: 'kamabhumi', icon: 'fa-paw', desc: 'တိရစ္ဆာန် သတ္တဝါများ၏ ဘုံ — အကုသိုလ်ကံ၏ အကျိုးဆက်။', example: 'တိရစ္ဆာန်အားလုံးသည် ဤဘုံတွင် ပဋိသန္ဓေယူကြသည်။' },
            { id: 3, key: 'petti', pali: 'Petti-visaya', name: 'ပြိတ္တာဘုံ', group: 'kamabhumi', icon: 'fa-ghost', desc: 'အစာရေစာ ငတ်မွတ်ခေါင်းပါးသော ပြိတ္တာဘုံ — အကုသိုလ်ကံ၏ အကျိုးဆက်။', example: 'အခါခပ်သိမ်း ငတ်ပြတ်နေသော ပြိတ္တာသတ္တဝါများ၏ ဘုံ။' },
            { id: 4, key: 'asurakaya', pali: 'Asurakāya', name: 'အသုရကာယ်ဘုံ', group: 'kamabhumi', icon: 'fa-user-ninja', desc: 'အသုရကာယ် သတ္တဝါများ၏ ဘုံ — အကုသိုလ်ကံ၏ အကျိုးဆက်။', example: 'အပါယ်ဘုံ (၄) ပါးအနက် နောက်ဆုံး ဘုံ။' },
            { id: 5, key: 'manussa', pali: 'Manussa', name: 'လူ့ဘုံ', group: 'kamabhumi', icon: 'fa-person', desc: 'ကုသိုလ်/အကုသိုလ် နှစ်မျိုးစလုံး ရောနှော ခံစားရသော ဘုံ — ဓမ္မအားထုတ်ရန် အသင့်လျော်ဆုံး ဘုံ ဟု ဆိုကြသည်။', example: 'သုခ/ဒုက္ခ နှစ်မျိုးလုံး ရောယှက် ခံစားရသဖြင့် သံဝေဂ ရလွယ်သော ဘုံ။' },
            { id: 6, key: 'catummaharajika', pali: 'Cātumahārājika', name: 'စတုမဟာရာဇ်ဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'ကာမာဝစရ နတ်ဘုံ (၆) ပါးအနက် ပထမဆုံး — မင်းကြီး (၄) ပါး အုပ်ချုပ်သော ဘုံ။', example: 'လူ့ဘုံနှင့် အနီးဆုံး နတ်ဘုံ။' },
            { id: 7, key: 'tavatimsa', pali: 'Tāvatiṃsa', name: 'တာဝတိံသာဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'သိကြားမင်း အုပ်ချုပ်သော ကာမာဝစရ နတ်ဘုံ။', example: 'နတ်မင်းသိကြား နေထိုင်ရာ ဘုံ။' },
            { id: 8, key: 'yama', pali: 'Yāma', name: 'ယာမာဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'ကာမာဝစရ နတ်ဘုံ (၆) ပါးအနက် (၃) ခုမြောက်။', example: 'ယာမာနတ်မင်း အုပ်ချုပ်သော ဘုံ။' },
            { id: 9, key: 'tusita', pali: 'Tusita', name: 'တုသိတာဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'ဘုရားလောင်းများ မှတ်တမ်းတင် ချီးမြှင့်ခံရလေ့ရှိသော ကာမာဝစရ နတ်ဘုံ။', example: 'ဘုရားဖြစ်ခါနီး ဗောဓိသတ္တာများ နေထိုင်လေ့ရှိသော ဘုံ။' },
            { id: 10, key: 'nimmanarati', pali: 'Nimmānarati', name: 'နိမ္မာနရတိဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'မိမိဖန်ဆင်းသော ကာမဂုဏ်ဖြင့် ပျော်မွေ့သော ကာမာဝစရ နတ်ဘုံ။', example: 'လိုချင်သည့်အရာကို မိမိဖန်ဆင်း၍ ခံစားနိုင်သော ဘုံ။' },
            { id: 11, key: 'paranimmitavasavatti', pali: 'Paranimmitavasavatti', name: 'ပရနိမ္မိတဝသဝတ္တီဘုံ', group: 'kamabhumi', icon: 'fa-crown', desc: 'အခြားသူ ဖန်ဆင်းပေးသော ကာမဂုဏ်ဖြင့် ပျော်မွေ့သော ကာမာဝစရ နတ်ဘုံ (၆) ပါးအနက် အမြင့်ဆုံး ဘုံ။', example: 'မာရ်နတ်မင်း နေထိုင်ရာ ဘုံ။' },

            // Rupabhumi (16) — sky
            { id: 12, key: 'brahmaparisajja', pali: 'Brahmapārisajjā', name: 'ဗြဟ္မပါရိသဇ္ဇာဘုံ', group: 'rupabhumi', icon: 'fa-mountain', desc: 'ပဌမဈာန်ဘုံ (၃) ပါးအနက် အနိမ့်ဆုံး — ပဌမဈာန် ပရိတ္တအဆင့်ဖြင့် ရရှိသော ဘုံ။', example: 'ပရိတ္တ ပဌမဈာန် ရရှိသူ ပဋိသန္ဓေယူရာ ဘုံ။' },
            { id: 13, key: 'brahmapurohita', pali: 'Brahmapurohitā', name: 'ဗြဟ္မပုရောဟိတာဘုံ', group: 'rupabhumi', icon: 'fa-mountain', desc: 'ပဌမဈာန် မဇ္ဈိမအဆင့်ဖြင့် ရရှိသော ဘုံ။', example: 'ပဌမဈာန်ဘုံ (၃) ပါးအနက် အလယ်အလတ်။' },
            { id: 14, key: 'mahabrahma', pali: 'Mahābrahmā', name: 'မဟာဗြဟ္မာဘုံ', group: 'rupabhumi', icon: 'fa-mountain', desc: 'ပဌမဈာန် ပဏီတ (အထွဋ်အမြတ်) အဆင့်ဖြင့် ရရှိသော ဘုံ။', example: 'ပဌမဈာန်ဘုံ (၃) ပါးအနက် အမြင့်ဆုံး။' },
            { id: 15, key: 'parittabha', pali: 'Parittābhā', name: 'ပရိတ္တာဘာဘုံ', group: 'rupabhumi', icon: 'fa-mountain-sun', desc: 'ဒုတိယဈာန်ဘုံ (၃) ပါးအနက် အနိမ့်ဆုံး — ရောင်ခြည် အနည်းငယ်သာ ထွန်းလင်းသော ဘုံ။', example: 'ဒုတိယဈာန် ပရိတ္တအဆင့်ဖြင့် ရရှိသော ဘုံ။' },
            { id: 16, key: 'appamanabha', pali: 'Appamāṇābhā', name: 'အပ္ပမာဏာဘာဘုံ', group: 'rupabhumi', icon: 'fa-mountain-sun', desc: 'ဒုတိယဈာန် မဇ္ဈိမအဆင့်ဖြင့် ရရှိသော ဘုံ — ရောင်ခြည် မရေတွက်နိုင်အောင် ထွန်းလင်းသည်။', example: 'ဒုတိယဈာန်ဘုံ (၃) ပါးအနက် အလယ်အလတ်။' },
            { id: 17, key: 'abhassara', pali: 'Ābhassarā', name: 'အာဘဿရာဘုံ', group: 'rupabhumi', icon: 'fa-mountain-sun', desc: 'ဒုတိယဈာန် ပဏီတအဆင့်ဖြင့် ရရှိသော ဘုံ — ရောင်ခြည် တောက်ပစွာ ထွန်းလင်းသည်။', example: 'ကမ္ဘာပျက်ချိန်တွင် သတ္တဝါအများစု ဤဘုံတွင် ခိုလှုံလေ့ရှိသည်ဟု ဆိုသည်။' },
            { id: 18, key: 'parittasubha', pali: 'Parittasubhā', name: 'ပရိတ္တသုဘာဘုံ', group: 'rupabhumi', icon: 'fa-gem', desc: 'တတိယဈာန်ဘုံ (၃) ပါးအနက် အနိမ့်ဆုံး — အလှတန်ဆာ အနည်းငယ်သာ ရှိသော ဘုံ။', example: 'တတိယဈာန် ပရိတ္တအဆင့်ဖြင့် ရရှိသော ဘုံ။' },
            { id: 19, key: 'appamanasubha', pali: 'Appamāṇasubhā', name: 'အပ္ပမာဏသုဘာဘုံ', group: 'rupabhumi', icon: 'fa-gem', desc: 'တတိယဈာန် မဇ္ဈိမအဆင့်ဖြင့် ရရှိသော ဘုံ။', example: 'တတိယဈာန်ဘုံ (၃) ပါးအနက် အလယ်အလတ်။' },
            { id: 20, key: 'subhakinha', pali: 'Subhakiṇhā', name: 'သုဘကိဏှာဘုံ', group: 'rupabhumi', icon: 'fa-gem', desc: 'တတိယဈာန် ပဏီတအဆင့်ဖြင့် ရရှိသော ဘုံ — အလှတန်ဆာ ပြည့်စုံစွာ ရှိသော ဘုံ။', example: 'တတိယဈာန်ဘုံ (၃) ပါးအနက် အမြင့်ဆုံး။' },
            { id: 21, key: 'vehapphala', pali: 'Vehapphalā', name: 'ဝေဟပ္ဖလာဘုံ', group: 'rupabhumi', icon: 'fa-cloud', desc: 'စတုတ္ထဈာန်ဖြင့် ရရှိသော ဘုံ — ဖလကြီးသော ဘုံ ဟု အနက်ရှိသည်။', example: 'ရူပါဝစရဘုံများအနက် တည်ငြိမ်ဆုံးဘုံ ဟု ဆိုကြသည်။' },
            { id: 22, key: 'asannasatta', pali: 'Asaññasatta', name: 'အသညသတ်ဘုံ', group: 'rupabhumi', icon: 'fa-cloud', desc: 'စိတ် (နာမ်ခန္ဓာ) လုံးဝ မရှိဘဲ ရုပ်ခန္ဓာတစ်ခုတည်းဖြင့်သာ တည်ရှိနေသော ထူးခြားသော ဘုံ။', example: 'ဤဘုံတွင် ရုပ်တစ်ခုတည်း (ဇီဝိတနဝကကလာပ်) သာ ဆက်တိုက် တည်ရှိနေသည်။' },
            { id: 23, key: 'aviha', pali: 'Avihā', name: 'အဝိဟာဘုံ', group: 'rupabhumi', icon: 'fa-star', desc: 'သုဒ္ဓါဝါသဘုံ (၅) ပါးအနက် ပထမ — အနာဂါမီပုဂ္ဂိုလ်များသာ ပဋိသန္ဓေယူနိုင်သော ဘုံ။', example: 'ရဟန္တာ မဖြစ်မီ ဤဘုံတွင် နောက်ဆုံးအကြိမ် ပဋိသန္ဓေယူတတ်သည်။' },
            { id: 24, key: 'atappa', pali: 'Atappā', name: 'အတပ္ပာဘုံ', group: 'rupabhumi', icon: 'fa-star', desc: 'သုဒ္ဓါဝါသဘုံ (၅) ပါးအနက် ဒုတိယ — အနာဂါမီပုဂ္ဂိုလ်များသာ ပဋိသန္ဓေယူနိုင်သော ဘုံ။', example: 'သုဒ္ဓါဝါသဘုံငါးခုစလုံးကို အနာဂါမီပုဂ္ဂိုလ်များသာ ပဋိသန္ဓေယူနိုင်သည်။' },
            { id: 25, key: 'sudassa', pali: 'Sudassā', name: 'သုဒဿာဘုံ', group: 'rupabhumi', icon: 'fa-star', desc: 'သုဒ္ဓါဝါသဘုံ (၅) ပါးအနက် တတိယ။', example: 'အနာဂါမီပုဂ္ဂိုလ်များသာ ပဋိသန္ဓေယူနိုင်သော ဘုံ။' },
            { id: 26, key: 'sudassi', pali: 'Sudassī', name: 'သုဒဿီဘုံ', group: 'rupabhumi', icon: 'fa-star', desc: 'သုဒ္ဓါဝါသဘုံ (၅) ပါးအနက် စတုတ္ထ။', example: 'အနာဂါမီပုဂ္ဂိုလ်များသာ ပဋိသန္ဓေယူနိုင်သော ဘုံ။' },
            { id: 27, key: 'akanittha', pali: 'Akaniṭṭhā', name: 'အကနိဋ္ဌာဘုံ', group: 'rupabhumi', icon: 'fa-star', desc: 'သုဒ္ဓါဝါသဘုံ (၅) ပါးအနက် အမြင့်ဆုံး — ရူပါဝစရဘုံများအနက် အမြင့်ဆုံးဘုံလည်း ဖြစ်သည်။', example: 'ဤဘုံမှ အနာဂါမီပုဂ္ဂိုလ်များ ရဟန္တာ ဖြစ်၍ ပရိနိဗ္ဗာန်စံလေ့ရှိသည်။' },

            // Arupabhumi (4) — amber
            { id: 28, key: 'akasanancayatana', pali: 'Ākāsānañcāyatana', name: 'အာကာသာနဉ္စာယတနဘုံ', group: 'arupabhumi', icon: 'fa-expand', desc: 'ပဌမ အရူပဈာန် (အာကာသ-မိုးကောင်းကင် အနန္တသဘောကို အာရုံပြု) ဖြင့် ရရှိသော ဘုံ။', example: 'ရူပစဉ်ဆင်းရဲမှုကို ရှောင်ရှားလို၍ မိုးကောင်းကင်ကို အကန့်အသတ်မရှိ ဟု ရှုမှတ်ခြင်းမှ ဖြစ်သည်။' },
            { id: 29, key: 'vinnanancayatana', pali: 'Viññāṇañcāyatana', name: 'ဝိညာဏဉ္စာယတနဘုံ', group: 'arupabhumi', icon: 'fa-brain', desc: 'ဒုတိယ အရူပဈာန် (ပဌမ အရူပဈာန်ဝိညာဉ်ကို အာရုံပြု) ဖြင့် ရရှိသော ဘုံ။', example: 'ရှေးဈာန်ဝိညာဉ်ကို "အနန္တ" ဟု ရှုမှတ်ခြင်းမှ ဖြစ်သည်။' },
            { id: 30, key: 'akincannayatana', pali: 'Ākiñcaññāyatana', name: 'အာကိဉ္စညာယတနဘုံ', group: 'arupabhumi', icon: 'fa-circle-notch', desc: 'တတိယ အရူပဈာန် (ပဌမ အရူပဈာန်ဝိညာဉ် ကွယ်ပျောက်သွားပြီ ဟူသော "မရှိခြင်း" ကို အာရုံပြု) ဖြင့် ရရှိသော ဘုံ။', example: '"တစ်စုံတစ်ခုမျှ မရှိတော့" ဟူသော သဘောကို အာရုံပြု ရှုမှတ်ခြင်းမှ ဖြစ်သည်။' },
            { id: 31, key: 'nevasannanasannayatana', pali: 'Nevasaññānāsaññāyatana', name: 'နေဝသညာနာသညာယတနဘုံ', group: 'arupabhumi', icon: 'fa-yin-yang', desc: 'စတုတ္ထ အရူပဈာန် (တတိယ အရူပဈာန်ကို အလွန်သိမ်မွေ့စွာ အာရုံပြု) ဖြင့် ရရှိသော ဘုံ — ရူပါဝစရ/အရူပါဝစရဘုံများအနက် အမြင့်ဆုံး၊ သညာ ရှိသည်လည်း မဆို၊ မရှိသည်လည်း မဆိုနိုင်လောက်အောင် သိမ်မွေ့သော ဘုံ။', example: 'သံသရာတွင် ရရှိနိုင်သမျှ အမြင့်ဆုံး ဘဝ ဖြစ်သော်လည်း၊ နိစ္စမမြဲသေးသဖြင့် သံသရာမှ လွတ်မြောက်ခြင်း မဟုတ်သေးပေ။' }
        ];