const kilesaData = [
            // Asava (4) — rose — "intoxicating outflows"
            { id: 1, key: 'kamasava', pali: 'Kāmāsava', name: 'ကာမာသဝ', group: 'asava', icon: 'fa-fire',
              desc: 'ကာမဂုဏ်အာရုံများကို တပ်မက်မှု — စိတ်ကို "ယိုစိမ့်" စေတတ်သော အာသဝ။',
              example: 'အနှစ်ပေါင်းများစွာ ကာမဂုဏ်ကို လိုက်စားနေမိသော အလေ့အထ။' },
            { id: 2, key: 'bhavasava', pali: 'Bhavāsava', name: 'ဘဝါသဝ', group: 'asava', icon: 'fa-infinity',
              desc: 'ဘဝသစ် ဆက်လက် တည်ရှိလိုမှု (ဈာန်ဂုဏ်၊ ရုပ်/အရူပဘဝ) ကို တပ်မက်မှု။',
              example: 'ဗြဟ္မာဘဝကဲ့သို့ ထာဝရ တည်ရှိနေလိုသော တပ်မက်မှု။' },
            { id: 3, key: 'ditthasava', pali: 'Diṭṭhāsava', name: 'ဒိဋ္ဌါသဝ', group: 'asava', icon: 'fa-ban',
              desc: 'အယူမှား (မိစ္ဆာဒိဋ္ဌိ) ကို စွဲမြဲစွာ ကိုင်ထားမှု။',
              example: '"ကံနှင့် ကံ၏အကျိုး မရှိ" ဟူသော အယူမှားကို စွဲမြဲစွာ ယုံကြည်ခြင်း။' },
            { id: 4, key: 'avijjasava', pali: 'Avijjāsava', name: 'အဝိဇ္ဇာသဝ', group: 'asava', icon: 'fa-cloud',
              desc: 'သစ္စာလေးပါးကို မသိခြင်း — အာသဝ (၄) ပါးအနက် အခြေခံဆုံး။',
              example: 'ဒုက္ခ၏ အစစ်အမှန် သဘောကို လုံးဝ နားမလည်ခြင်း။' },

            // Ogha (4) — orange — "floods that sweep beings away"
            { id: 5, key: 'kamogha', pali: 'Kāmogha', name: 'ကာမောဃ', group: 'ogha', icon: 'fa-water',
              desc: 'ကာမတပ်မက်မှုသည် သတ္တဝါများကို သံသရာရေထဲ "မျှော" စေတတ်သော ဩဃ (ရေလွှမ်းမိုးမှု)။',
              example: 'ကာမဂုဏ် အလိုက် ဆွဲငင်ခံရသဖြင့် သံသရာမှ မလွတ်မြောက်နိုင်ခြင်း။' },
            { id: 6, key: 'bhavogha', pali: 'Bhavogha', name: 'ဘဝေါဃ', group: 'ogha', icon: 'fa-water',
              desc: 'ဘဝတွင် ဆက်လက် တည်ရှိလိုမှုသည် သတ္တဝါများကို "မျှော" စေတတ်သော ဩဃ။',
              example: 'ဘဝသစ် ဆက်လက် တောင့်တနေမှုက သံသရာစက်ဝန်းကို ဆက်လည်စေခြင်း။' },
            { id: 7, key: 'ditthogha', pali: 'Diṭṭhogha', name: 'ဒိဋ္ဌောဃ', group: 'ogha', icon: 'fa-water',
              desc: 'အယူမှားသည် သတ္တဝါများကို လမ်းမှားဘက်သို့ "မျှော" စေတတ်သော ဩဃ။',
              example: 'အယူမှားကို လိုက်နာကျင့်သုံးသဖြင့် အကျိုးရှိသော လမ်းကို လွဲချော်ခြင်း။' },
            { id: 8, key: 'avijjogha', pali: 'Avijjogha', name: 'အဝိဇ္ဇောဃ', group: 'ogha', icon: 'fa-water',
              desc: 'အသိဉာဏ် ကင်းမဲ့ခြင်းသည် သတ္တဝါများကို မှောင်ရေတွင်း၌ "မျှော" စေတတ်သော ဩဃ။',
              example: 'အမှန်တရားကို လုံးဝ မမြင်နိုင်သဖြင့် ရေအတွင်းကဲ့သို့ ခေါင်းငုံနစ်မြုပ်နေခြင်း။' },

            // Yoga (4) — amber — "yokes that bind to the round"
            { id: 9, key: 'kamayoga', pali: 'Kāmayoga', name: 'ကာမယောဂ', group: 'yoga', icon: 'fa-link',
              desc: 'ကာမတပ်မက်မှုသည် သတ္တဝါများကို ကာမဘဝနှင့် ချည်နှောင်ထားသော ယောက်ကန်။',
              example: 'နွားကို ယောက်ကန်ဖြင့် လှည်းနှင့် ချည်နှောင်ထားသကဲ့သို့၊ ကာမတပ်မက်မှုက ကာမဘုံနှင့် ချည်နှောင်ထားခြင်း။' },
            { id: 10, key: 'bhavayoga', pali: 'Bhavayoga', name: 'ဘဝယောဂ', group: 'yoga', icon: 'fa-link',
              desc: 'ဘဝ ဆက်လက် တည်ရှိလိုမှုသည် သတ္တဝါများကို သံသရာနှင့် ချည်နှောင်ထားသော ယောက်ကန်။',
              example: 'ဗြဟ္မာဘဝကို တောင့်တမှုက ထိုဘဝနှင့် ချည်နှောင်ထားခြင်း။' },
            { id: 11, key: 'ditthiyoga', pali: 'Diṭṭhiyoga', name: 'ဒိဋ္ဌိယောဂ', group: 'yoga', icon: 'fa-link',
              desc: 'အယူမှားသည် သတ္တဝါများကို မှားယွင်းသော အမြင်နှင့် ချည်နှောင်ထားသော ယောက်ကန်။',
              example: 'အယူမှားကို စွဲမြဲစွာ ကိုင်စွဲနေသဖြင့် အမှန်တရားကို လက်လွှတ်ရဲခြင်း မရှိခြင်း။' },
            { id: 12, key: 'avijjayoga', pali: 'Avijjāyoga', name: 'အဝိဇ္ဇာယောဂ', group: 'yoga', icon: 'fa-link',
              desc: 'အသိဉာဏ် ကင်းမဲ့ခြင်းသည် သတ္တဝါများကို မသိမှုနှင့် ချည်နှောင်ထားသော ယောက်ကန်။',
              example: 'သစ္စာလေးပါးကို မသိသဖြင့် ဆက်လက် ပတ်လမ်းလွဲနေခြင်း။' },

            // Gantha (4) — lime — "knots that tie mind to body/existence"
            { id: 13, key: 'abhijjhakayagantha', pali: 'Abhijjhā-kāyagantha', name: 'အဘိဇ္ဈာကာယဂန္ထ', group: 'gantha', icon: 'fa-link',
              desc: 'လောဘသည် နာမ်ကိုယ်ကို ရုပ်ကိုယ်နှင့် ဆက်စပ်နေစေသော အနှောင်အဖွဲ့။',
              example: 'သူတစ်ပါး ပိုင်ဆိုင်မှုကို အလွန် လိုချင်တပ်မက်ခြင်း။' },
            { id: 14, key: 'byapadakayagantha', pali: 'Byāpāda-kāyagantha', name: 'ဗျာပါဒကာယဂန္ထ', group: 'gantha', icon: 'fa-link',
              desc: 'ဒေါသသည် နာမ်ကိုယ်ကို ရုပ်ကိုယ်နှင့် ဆက်စပ်နေစေသော အနှောင်အဖွဲ့။',
              example: 'သူတစ်ပါးအား မုန်းတီး ဖျက်ဆီးလိုသော စိတ်။' },
            { id: 15, key: 'silabbataparamasakayagantha', pali: 'Sīlabbataparāmāsa-kāyagantha', name: 'သီလဗ္ဗတပရာမာသကာယဂန္ထ', group: 'gantha', icon: 'fa-link',
              desc: 'အကျိုးမရှိသော အလေ့အကျင့်/ထုံးတမ်းများကို "ဤသည်ကသာ စင်ကြယ်ရာလမ်း" ဟု စွဲလမ်းမှု။',
              example: 'တိရစ္ဆာန်ကဲ့သို့ ကျင့်ကြံခြင်းက ကောင်းရာသို့ ရောက်စေမည်ဟု အယူမှားစွာ စွဲလမ်းခြင်း။' },
            { id: 16, key: 'idamsaccabhinivesakayagantha', pali: 'Idaṃsaccābhinivesa-kāyagantha', name: 'ဣဒံသစ္စာဘိနိဝေသကာယဂန္ထ', group: 'gantha', icon: 'fa-link',
              desc: '"ငါ့အမြင်သာ မှန်၊ ကျန်သူများ အမှား" ဟု ခိုင်မြဲစွာ စွဲလမ်းမှု။',
              example: 'မိမိ၏ အယူအဆကိုသာ တစ်ခုတည်း မှန်ကန်သည်ဟု တင်းကျပ်စွာ ခံယူထားခြင်း။' },

            // Upadana (4) — emerald — "clinging" (also nidana #9 in Paticcasamuppada)
            { id: 17, key: 'kamupadana', pali: 'Kāmupādāna', name: 'ကာမုပါဒါန်', group: 'upadana', icon: 'fa-hand-fist',
              desc: 'ကာမဂုဏ်အာရုံများကို ခိုင်မြဲစွာ ဆုပ်ကိုင် တွယ်တာမှု — တဏှာ ပြင်းထန်လာသည့် အဆင့်။',
              example: '"ငါ့ဥစ္စာ ဖြစ်ရမည်" ဟု ခိုင်မြဲစွာ ဆုပ်ကိုင် လိုချင်မှု။' },
            { id: 18, key: 'ditthupadana', pali: 'Diṭṭhupādāna', name: 'ဒိဋ္ဌုပါဒါန်', group: 'upadana', icon: 'fa-hand-fist',
              desc: 'အယူမှား (သက္ကာယဒိဋ္ဌိ/သီလဗ္ဗတပရာမာသ/ဣဒံသစ္စာဘိနိဝေသ မှလွဲ၍ ကျန်အယူမှားများ) ကို ခိုင်မြဲစွာ ဆုပ်ကိုင်မှု။',
              example: 'ကမ္ဘာသည် ထာဝရ တည်တံ့သည် (သို့) ပျက်စီးသွားမည် ဟူသော အလွန်အမင်း အယူများကို စွဲစွဲမြဲမြဲ ကိုင်ထားခြင်း။' },
            { id: 19, key: 'silabbatupadana', pali: 'Sīlabbatupādāna', name: 'သီလဗ္ဗတုပါဒါန်', group: 'upadana', icon: 'fa-hand-fist',
              desc: 'အကျိုးမရှိသော ဘာသာရေး အလေ့အကျင့်များကို ခိုင်မြဲစွာ ဆုပ်ကိုင်မှု (ဂန္ထထက် ပို၍ ပြင်းထန်သော အဆင့်)။',
              example: 'တိရစ္ဆာန်ကဲ့သို့ ကျင့်ကြံခြင်းသာ လွတ်မြောက်ရာလမ်း ဟု ခိုင်ခိုင်မြဲမြဲ ယုံကြည် ကျင့်သုံးနေခြင်း။' },
            { id: 20, key: 'attavadupadana', pali: 'Attavādupādāna', name: 'အတ္တဝါဒုပါဒါန်', group: 'upadana', icon: 'fa-hand-fist',
              desc: '"ငါ" ဟူသော အနှစ်သာရ ခိုင်မြဲစွာ ရှိသည် ဟူသော သက္ကာယဒိဋ္ဌိကို ခိုင်မြဲစွာ ဆုပ်ကိုင်မှု။',
              example: 'ခန္ဓာငါးပါးအနက် တစ်ပါးပါးကို "ငါ" (သို့) "ငါ့ဝိညာဉ်" ဟု ခိုင်မြဲစွာ ယူဆထားခြင်း။' },

            // Nivarana (6) — cyan — "hindrances that block wholesome states"
            { id: 21, key: 'kamacchanda', pali: 'Kāmacchanda', name: 'ကာမစ္ဆန္ဒ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'ကာမဂုဏ်အာရုံကို လိုလားမှုသည် သမာဓိ ဖြစ်ပေါ်ခြင်းကို ဟန့်တားသော နီဝရဏ။',
              example: 'ဘာဝနာအားထုတ်နေစဉ် ကာမဂုဏ်ဆိုင်ရာ အတွေးများ ဝင်ရောက် နှောင့်ယှက်ခြင်း။' },
            { id: 22, key: 'byapada', pali: 'Byāpāda', name: 'ဗျာပါဒ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'ဒေါသ/အမျက်ဒေါသသည် သမာဓိ ဖြစ်ပေါ်ခြင်းကို ဟန့်တားသော နီဝရဏ။',
              example: 'ဘာဝနာအားထုတ်နေစဉ် စိတ်ဆိုးမှု၊ ခံစားရသည့် မကျေနပ်မှု ပေါ်လာခြင်း။' },
            { id: 23, key: 'thinamiddha', pali: 'Thīnamiddha', name: 'ထိနမိဒ္ဓ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'စိတ်ညောင်းညာမှု (ထိန) နှင့် စေတသိက်ညောင်းညာမှု (မိဒ္ဓ) — အိပ်ငိုက်ချင် ပျင်းရိမှု။',
              example: 'ဘာဝနာအားထုတ်နေစဉ် အိပ်ငိုက်လာခြင်း၊ စိတ်ဓာတ် ညောင်းညာလာခြင်း။' },
            { id: 24, key: 'uddhaccakukkucca', pali: 'Uddhaccakukkucca', name: 'ဥဒ္ဓစ္စကုက္ကုစ္စ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'စိတ်ပျံ့လွင့်မှု (ဥဒ္ဓစ္စ) နှင့် ကျူးလွန်ခဲ့သော အမှားအတွက် နောင်တရမှု (ကုက္ကုစ္စ)။',
              example: 'ဘာဝနာအားထုတ်နေစဉ် အတိတ်က ပြုမိသော အမှားများကို ပြန်တွေးမိ စိတ်မငြိမ်ဖြစ်ခြင်း။' },
            { id: 25, key: 'vicikiccha_niv', pali: 'Vicikicchā', name: 'ဝိစိကိစ္ဆာ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'ရတနာသုံးပါး၊ ကံနှင့် ကံ၏အကျိုး၌ ယုံမှားသံသယ ဖြစ်ခြင်း။',
              example: '"ဘာဝနာအားထုတ်ခြင်းက တကယ် အကျိုးရှိမည်လား" ဟု ယုံမှားခြင်း။' },
            { id: 26, key: 'avijja_niv', pali: 'Avijjā', name: 'အဝိဇ္ဇာ', group: 'nivarana', icon: 'fa-eye-low-vision',
              desc: 'သစ္စာလေးပါးကို မသိခြင်းသည် အမှန်တရား သိမြင်ခြင်းကို ဟန့်တားသော နီဝရဏ။',
              example: 'ဒုက္ခ၏ အစစ်အမှန် သဘောကို လုံးဝ နားမလည်ခြင်း။' },

            // Anusaya (7) — indigo — "latent tendencies dormant in the mind-stream"
            { id: 27, key: 'kamaraganusaya', pali: 'Kāmarāgānusaya', name: 'ကာမရာဂါနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'ကာမတပ်မက်မှု၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား — အခွင့်ကောင်း ရလျှင် ချက်ချင်း ပေါ်လွင်လာနိုင်သည်။',
              example: 'ရေရှည် ကာမဂုဏ်ကို မတွေ့ကြုံသေးသော်လည်း၊ ရုတ်တရက် တွေ့လျှင် လောဘ ချက်ချင်း ပေါ်လာနိုင်ခြင်း။' },
            { id: 28, key: 'bhavaraganusaya', pali: 'Bhavarāgānusaya', name: 'ဘဝရာဂါနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'ဘဝတွင် ဆက်လက် တည်ရှိလိုမှု၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား။',
              example: 'ယခု အသက်ရှင်နေချိန်တွင် သိသိသာသာ မပေါ်သော်လည်း၊ သေခါနီးတွင် ပေါ်လွင်လာနိုင်ခြင်း။' },
            { id: 29, key: 'patighanusaya', pali: 'Paṭighānusaya', name: 'ပဋိဃာနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'ဒေါသ၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား။',
              example: 'ပုံမှန်အခါ စိတ်ငြိမ်နေသော်လည်း၊ လှုံ့ဆော်မှု ရလျှင် ချက်ချင်း ဒေါသ ပေါ်လွင်လာနိုင်ခြင်း။' },
            { id: 30, key: 'mananusaya', pali: 'Mānānusaya', name: 'မာနာနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: '"ငါ" ဟု ဂုဏ်ယူ ထောင်လွှားမှု၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား။',
              example: 'ယှဉ်ပြိုင်ရသော အခြေအနေတွင် "ငါက ပိုကောင်း/ညံ့" ဟူသော နှိုင်းယှဉ်စိတ် ချက်ချင်း ပေါ်လာခြင်း။' },
            { id: 31, key: 'ditthanusaya', pali: 'Diṭṭhānusaya', name: 'ဒိဋ္ဌာနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'အယူမှား၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား။',
              example: 'သင်ကြားခံရလျှင် အယူမှား ချက်ချင်း ပြန်ပေါ်လာနိုင်ခြင်း။' },
            { id: 32, key: 'vicikicchanusaya', pali: 'Vicikicchānusaya', name: 'ဝိစိကိစ္ဆာနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'ယုံမှားသံသယ၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား။',
              example: 'ယုံကြည်မှု ရှိသည်ဟု ထင်ရသော်လည်း၊ စမ်းသပ်ခံရလျှင် သံသယ ပြန်ပေါ်လာနိုင်ခြင်း။' },
            { id: 33, key: 'avijjanusaya', pali: 'Avijjānusaya', name: 'အဝိဇ္ဇာနုသယ', group: 'anusaya', icon: 'fa-seedling',
              desc: 'အသိဉာဏ် ကင်းမဲ့ခြင်း၏ ကိန်းအောင်းလျက် ရှိနေသော နောက်ခံ သဘောတရား — အနုသယ (၇) ပါးအနက် အခြေခံဆုံး။',
              example: 'ဤအနုသယ (၇) ပါးလုံးကို မဂ်ဉာဏ်အဆင့်အလိုက် တစ်ခုစီ အပြီးအပိုင် ပယ်ဖျက်နိုင်မှသာ ရဟန္တာ ဖြစ်နိုင်သည်။' },

            // Samyojana (10, Abhidhamma method) — violet — "fetters that bind to samsara"
            { id: 34, key: 'kamaraga_sam', pali: 'Kāmarāga', name: 'ကာမရာဂ (သံယောဇဉ်)', group: 'samyojana', icon: 'fa-chain',
              desc: 'ကာမဘုံနှင့် ချည်နှောင်ထားသော သံယောဇဉ် — အနာဂါမီအဆင့်တွင် အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'ကာမဂုဏ်ကို လုံးဝ တပ်မက်ခြင်း မရှိတော့သည့် အနာဂါမီပုဂ္ဂိုလ်။' },
            { id: 35, key: 'ruparaga_sam', pali: 'Rūparāga', name: 'ရူပရာဂ', group: 'samyojana', icon: 'fa-chain',
              desc: 'ရူပဈာန်/ရူပဘဝကို တပ်မက်မှု — ရဟန္တာအဆင့်တွင်သာ အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'ရူပဈာန်ဂုဏ်ကို တောင့်တနေသေးသော အနာဂါမီပုဂ္ဂိုလ်။' },
            { id: 36, key: 'aruparaga_sam', pali: 'Arūparāga', name: 'အရူပရာဂ', group: 'samyojana', icon: 'fa-chain',
              desc: 'အရူပဈာန်/အရူပဘဝကို တပ်မက်မှု — ရဟန္တာအဆင့်တွင်သာ အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'အရူပဈာန်ဂုဏ်ကို တောင့်တနေသေးသော အနာဂါမီပုဂ္ဂိုလ်။' },
            { id: 37, key: 'patigha_sam', pali: 'Paṭigha', name: 'ပဋိဃ', group: 'samyojana', icon: 'fa-chain',
              desc: 'ဒေါသ (မကျေမနပ် စိတ်ထိခိုက်မှု) — အနာဂါမီအဆင့်တွင် အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'မကျေနပ်မှု အနည်းငယ်မျှပင် လုံးဝ မဖြစ်တော့သော အနာဂါမီပုဂ္ဂိုလ်။' },
            { id: 38, key: 'mana_sam', pali: 'Māna', name: 'မာန', group: 'samyojana', icon: 'fa-chain',
              desc: 'ငါ့ကိုယ်ကို နှိုင်းယှဉ် ဂုဏ်ယူမှု — ရဟန္တာအဆင့်တွင်သာ အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'သိမ်မွေ့သော နှိုင်းယှဉ်စိတ် ကျန်ရှိနေသေးသော အနာဂါမီပုဂ္ဂိုလ်။' },
            { id: 39, key: 'ditthi_sam', pali: 'Diṭṭhi', name: 'ဒိဋ္ဌိ', group: 'samyojana', icon: 'fa-chain',
              desc: 'အယူမှား (သက္ကာယဒိဋ္ဌိအပါအဝင်) — သောတာပန်အဆင့်တွင် အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: '"ခန္ဓာသည် ငါ ဖြစ်သည်" ဟူသော အယူမှား ပြတ်တောက်သွားသော သောတာပန်ပုဂ္ဂိုလ်။' },
            { id: 40, key: 'silabbataparamasa_sam', pali: 'Sīlabbataparāmāsa', name: 'သီလဗ္ဗတပရာမာသ', group: 'samyojana', icon: 'fa-chain',
              desc: 'အကျိုးမရှိသော အလေ့အကျင့်ကို စွဲလမ်းမှု — သောတာပန်အဆင့်တွင် အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'တိရစ္ဆာန်ကျင့်စဉ်များကို လွတ်မြောက်ရာလမ်းဟု လုံးဝ မထင်မှားတော့သော သောတာပန်ပုဂ္ဂိုလ်။' },
            { id: 41, key: 'vicikiccha_sam', pali: 'Vicikicchā', name: 'ဝိစိကိစ္ဆာ (သံယောဇဉ်)', group: 'samyojana', icon: 'fa-chain',
              desc: 'ရတနာသုံးပါးအပေါ် ယုံမှားသံသယ — သောတာပန်အဆင့်တွင် အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'ရတနာသုံးပါးအပေါ် တည်ကြည်စွာ ယုံကြည်ပြီး၊ သံသယ လုံးဝ ကင်းစင်သွားသော သောတာပန်ပုဂ္ဂိုလ်။' },
            { id: 42, key: 'uddhacca_sam', pali: 'Uddhacca', name: 'ဥဒ္ဓစ္စ', group: 'samyojana', icon: 'fa-chain',
              desc: 'စိတ်ပျံ့လွင့်မှု — ရဟန္တာအဆင့်တွင်သာ အပြီးအပိုင် ပြတ်တောက်သည် (အနုသင်္ခာရဟန္တာအထိ ကျန်ရှိနိုင်)။',
              example: 'အလွန်သိမ်မွေ့သော စိတ်လှုပ်ရှားမှု ကျန်ရှိနေသေးသော အရိယာပုဂ္ဂိုလ်။' },
            { id: 43, key: 'avijja_sam', pali: 'Avijjā', name: 'အဝိဇ္ဇာ (သံယောဇဉ်)', group: 'samyojana', icon: 'fa-chain',
              desc: 'အသိဉာဏ် ကင်းမဲ့ခြင်း — ရဟန္တာအဆင့်တွင်သာ အပြီးအပိုင် ပြတ်တောက်သည်။',
              example: 'သစ္စာလေးပါးကို အပြည့်အဝ ထိုးထွင်း သိမြင်ပြီးဖြစ်သော ရဟန္တာပုဂ္ဂိုလ်။' },

            // Kilesa (10) — pink — "defilements that afflict the mind"
            { id: 44, key: 'lobha_kil', pali: 'Lobha', name: 'လောဘ', group: 'kilesa', icon: 'fa-magnet',
              desc: 'အာရုံကို လိုလားတပ်မက်ခြင်း၊ တွယ်တာခြင်း။',
              example: 'ကာမဂုဏ်အာရုံများအပေါ် ပြင်းပြစွာ လိုချင်တပ်မက်ခြင်း။' },
            { id: 45, key: 'dosa_kil', pali: 'Dosa', name: 'ဒေါသ', group: 'kilesa', icon: 'fa-fire',
              desc: 'အာရုံကို မကျေနပ်ခြင်း၊ ကြမ်းတမ်းစွာ ဖျက်ဆီးလိုခြင်း။',
              example: 'မိမိအလိုနှင့် မကိုက်ညီသောအခါ ဒေါသထွက်ခြင်း၊ စိတ်ဆိုးခြင်း။' },
            { id: 46, key: 'moha_kil', pali: 'Moha', name: 'မောဟ', group: 'kilesa', icon: 'fa-cloud',
              desc: 'အာရုံ၏ အမှန်သဘောကို မသိခြင်း (အဝိဇ္ဇာ)။',
              example: 'အနိစ္စ, ဒုက္ခ, အနတ္တ ကို မသိဘဲ မြဲသည်, ချမ်းသာသည်ဟု ထင်မှတ်မှားခြင်း။' },
            { id: 47, key: 'mana_kil', pali: 'Māna', name: 'မာန', group: 'kilesa', icon: 'fa-arrow-up-right-dots',
              desc: 'မိမိကိုယ်ကို အခြားသူနှင့် နှိုင်းယှဉ်၍ ထောင်လွှားခြင်း။',
              example: 'ငါက ပိုသာသည် ဟု ဂုဏ်ယူဝင့်ကြွားခြင်း။' },
            { id: 48, key: 'ditthi_kil', pali: 'Diṭṭhi', name: 'ဒိဋ္ဌိ', group: 'kilesa', icon: 'fa-eye-slash',
              desc: 'မှားယွင်းသော အယူအဆကို စွဲကိုင်ထားခြင်း (မိစ္ဆာဒိဋ္ဌိ)။',
              example: 'ကံနှင့် ကံ၏အကျိုးကို မယုံကြည်ခြင်း။' },
            { id: 49, key: 'vicikiccha_kil', pali: 'Vicikicchā', name: 'ဝိစိကိစ္ဆာ', group: 'kilesa', icon: 'fa-question',
              desc: 'ရတနာသုံးပါး စသည်တို့၌ ယုံမှားသံသယဖြစ်ခြင်း။',
              example: 'ဘုရားရှင် တကယ်ရှိ/မရှိ သံသယဖြစ်ခြင်း။' },
            { id: 50, key: 'thina_kil', pali: 'Thīna', name: 'ထိန', group: 'kilesa', icon: 'fa-bed',
              desc: 'စိတ်၏ ထိုင်းမှိုင်းညောင်းညာမှု။',
              example: 'ကုသိုလ်လုပ်ငန်းများတွင် စိတ်မပါဘဲ လေးလံထိုင်းမှိုင်းနေခြင်း။' },
            { id: 51, key: 'uddhacca_kil', pali: 'Uddhacca', name: 'ဥဒ္ဓစ္စ', group: 'kilesa', icon: 'fa-wind',
              desc: 'စိတ်၏ ပျံ့လွင့်မှု၊ မငြိမ်မသက်ဖြစ်မှု။',
              example: 'အာရုံတစ်ခုတည်းပေါ်တွင် စိတ်မတည်ဘဲ ဟိုတွေးဒီတွေး ပျံ့လွင့်နေခြင်း။' },
            { id: 52, key: 'ahirika_kil', pali: 'Ahirika', name: 'အဟိရိက', group: 'kilesa', icon: 'fa-mask',
              desc: 'ဒုစရိုက် (မကောင်းမှု) ပြုလုပ်ရန် မရှက်ခြင်း။',
              example: 'မကောင်းမှုပြုလုပ်ရာတွင် ကိုယ်ကျင့်တရားအရ မရှက်ရွံ့ခြင်း။' },
            { id: 53, key: 'anottappa_kil', pali: 'Anottappa', name: 'အနောတ္တပ္ပ', group: 'kilesa', icon: 'fa-shield-halved',
              desc: 'ဒုစရိုက် (မကောင်းမှု) ပြုလုပ်ရန် မကြောက်ခြင်း။',
              example: 'အပါယ်ကျမည်ကို မကြောက်ဘဲ မကောင်းမှုများကို ရဲတင်းစွာ ပြုလုပ်ခြင်း။' }
        ];

