const sbData = [
            // Khandha (5) — indigo
            { id: 101, key: 'rupakkhandha', pali: 'Rūpakkhandha', name: 'ရူပက္ခန္ဓာ', group: 'khandha', icon: 'fa-cubes',
              desc: 'ရုပ်တရား (၂၈) ပါး အစုအဝေး။',
              example: 'အတိတ်/အနာဂတ်/ပစ္စုပ္ပန် စသည့် ရုပ်အားလုံးကို တစ်ပေါင်းတည်းပြု၍ ရူပက္ခန္ဓာဟု ခေါ်သည်။' },
            { id: 102, key: 'vedanakkhandha', pali: 'Vedanākkhandha', name: 'ဝေဒနာက္ခန္ဓာ', group: 'khandha', icon: 'fa-heart',
              desc: 'ဝေဒနာစေတသိက် တစ်ပါးတည်း အစုအဝေး။',
              example: 'စိတ် ၈၉ ပါးလုံး၌ ယှဉ်သော ဝေဒနာအားလုံး ပါဝင်သည်။' },
            { id: 103, key: 'sannakkhandha', pali: 'Saññākkhandha', name: 'သညာက္ခန္ဓာ', group: 'khandha', icon: 'fa-tag',
              desc: 'သညာစေတသိက် တစ်ပါးတည်း အစုအဝေး။',
              example: 'စိတ် ၈၉ ပါးလုံး၌ ယှဉ်သော မှတ်သားမှုသညာအားလုံး ပါဝင်သည်။' },
            { id: 104, key: 'sankharakkhandha', pali: 'Saṅkhārakkhandha', name: 'သင်္ခါရက္ခန္ဓာ', group: 'khandha', icon: 'fa-gears',
              desc: 'ဝေဒနာ၊ သညာ မှလွဲ၍ ကျန်သော စေတသိက် (၅၀) အစုအဝေး။',
              example: 'စိတ်ကို ပြုပြင်ပေးသော စေတနာ အစရှိသည့် တရားများ အားလုံး ပါဝင်သည်။' },
            { id: 105, key: 'vinnanakkhandha', pali: 'Viññāṇakkhandha', name: 'ဝိညာဏက္ခန္ဓာ', group: 'khandha', icon: 'fa-brain',
              desc: 'စိတ် (၈၉) ပါး အစုအဝေး။',
              example: 'လောကီရော လောကုတ္တရာပါ စိတ်အားလုံး ပါဝင်သည်။' },

            // Upadanakkhandha (5) — rose
            { id: 106, key: 'rupupadanakkhandha', pali: 'Rūpupādānakkhandha', name: 'ရူပုပါဒါနက္ခန္ဓာ', group: 'upadanakkhandha', icon: 'fa-cubes',
              desc: 'ဥပါဒါန်၏ အာရုံဖြစ်သော ရုပ်တရား (၂၈) ပါး အစုအဝေး။',
              example: 'ရုပ်အားလုံးသည် လောကီချည်းဖြစ်၍ ရူပက္ခန္ဓာနှင့် အတူတူပင်ဖြစ်သည်။' },
            { id: 107, key: 'vedanupadanakkhandha', pali: 'Vedanupādānakkhandha', name: 'ဝေဒနုပါဒါနက္ခန္ဓာ', group: 'upadanakkhandha', icon: 'fa-heart',
              desc: 'ဥပါဒါန်၏ အာရုံဖြစ်သော လောကီဝေဒနာ အစုအဝေး။',
              example: 'လောကီစိတ် (၈၁) ပါး၌ ယှဉ်သော ဝေဒနာကိုသာ ယူသည်။' },
            { id: 108, key: 'sannupadanakkhandha', pali: 'Saññupādānakkhandha', name: 'သညုပါဒါနက္ခန္ဓာ', group: 'upadanakkhandha', icon: 'fa-tag',
              desc: 'ဥပါဒါန်၏ အာရုံဖြစ်သော လောကီသညာ အစုအဝေး။',
              example: 'လောကီစိတ် (၈၁) ပါး၌ ယှဉ်သော သညာကိုသာ ယူသည်။' },
            { id: 109, key: 'sankharupadanakkhandha', pali: 'Saṅkhārupādānakkhandha', name: 'သင်္ခါရုပါဒါနက္ခန္ဓာ', group: 'upadanakkhandha', icon: 'fa-gears',
              desc: 'ဥပါဒါန်၏ အာရုံဖြစ်သော လောကီစေတသိက် (၅၀) အစုအဝေး။',
              example: 'လောကီစိတ်၌ ယှဉ်သော စေတသိက်များကိုသာ ယူသည်။' },
            { id: 110, key: 'vinnanupadanakkhandha', pali: 'Viññāṇupādānakkhandha', name: 'ဝိညာဏုပါဒါနက္ခန္ဓာ', group: 'upadanakkhandha', icon: 'fa-brain',
              desc: 'ဥပါဒါန်၏ အာရုံဖြစ်သော လောကီစိတ် (၈၁) ပါး အစုအဝေး။',
              example: 'လောကုတ္တရာစိတ် (၈) ပါးသည် ဥပါဒါန်၏ အာရုံ မဖြစ်နိုင်သဖြင့် ဤအစုတွင် မပါဝင်ပါ။' },

            // Ayatana internal (6) — sky
            { id: 1, key: 'cakkhayatana', pali: 'Cakkhāyatana', name: 'စက္ခာယတန', group: 'ayatana-internal', icon: 'fa-eye',
              desc: 'မျက်စိ၏ ပသာဒရုပ် — အဆင်းကို ခံစားနိုင်စွမ်းရှိသော အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "စက္ခုပသာဒ" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 2, key: 'sotayatana', pali: 'Sotāyatana', name: 'သောတာယတန', group: 'ayatana-internal', icon: 'fa-ear-listen',
              desc: 'နား၏ ပသာဒရုပ် — အသံကို ခံစားနိုင်စွမ်းရှိသော အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "သောတပသာဒ" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 3, key: 'ghanayatana', pali: 'Ghānāyatana', name: 'ဃာနာယတန', group: 'ayatana-internal', icon: 'fa-atom',
              desc: 'နှာခေါင်း၏ ပသာဒရုပ် — အနံ့ကို ခံစားနိုင်စွမ်းရှိသော အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ဃာနပသာဒ" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 4, key: 'jivhayatana', pali: 'Jivhāyatana', name: 'ဇိဝှါယတန', group: 'ayatana-internal', icon: 'fa-droplet',
              desc: 'လျှာ၏ ပသာဒရုပ် — အရသာကို ခံစားနိုင်စွမ်းရှိသော အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ဇိဝှါပသာဒ" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 5, key: 'kayayatana', pali: 'Kāyāyatana', name: 'ကာယာယတန', group: 'ayatana-internal', icon: 'fa-hand',
              desc: 'ကိုယ်ခန္ဓာ၏ ပသာဒရုပ် — အတွေ့ကို ခံစားနိုင်စွမ်းရှိသော အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ကာယပသာဒ" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 6, key: 'manayatana', pali: 'Manāyatana', name: 'မနာယတန', group: 'ayatana-internal', icon: 'fa-brain',
              desc: 'စိတ် (၈၉/၁၂၁ ပါးလုံး) — "မန" ဟု ခေါ်ဝေါ်သော အာယတန။',
              example: 'ဤတစ်ခုတည်းသည် ဤ Guide ၏ "စိတ် (၈၉) ပါး" tab တွင် လေ့လာခဲ့ပြီးသား ဇစ်မြစ်တစ်ခုလုံးကို ကိုယ်စားပြုသည်။' },

            // Ayatana external (6) — amber
            { id: 7, key: 'rupayatana', pali: 'Rūpāyatana', name: 'ရူပါယတန', group: 'ayatana-external', icon: 'fa-palette',
              desc: 'အဆင်းအာရုံ — စက္ခာယတန၏ ဆိုင်ရာ အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ဝဏ္ဏရုပ်" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 8, key: 'saddayatana', pali: 'Saddāyatana', name: 'သဒ္ဒါယတန', group: 'ayatana-external', icon: 'fa-volume-high',
              desc: 'အသံအာရုံ — သောတာယတန၏ ဆိုင်ရာ အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "သဒ္ဒရုပ်" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 9, key: 'gandhayatana', pali: 'Gandhāyatana', name: 'ဂန္ဓာယတန', group: 'ayatana-external', icon: 'fa-wind',
              desc: 'အနံ့အာရုံ — ဃာနာယတန၏ ဆိုင်ရာ အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ဂန္ဓရုပ်" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 10, key: 'rasayatana', pali: 'Rasāyatana', name: 'ရသာယတန', group: 'ayatana-external', icon: 'fa-utensils',
              desc: 'အရသာအာရုံ — ဇိဝှါယတန၏ ဆိုင်ရာ အာယတန။',
              example: 'ရူပသင်္ဂဟတွင် "ရသရုပ်" ဟု ခေါ်ဝေါ်ခဲ့သော ရုပ်တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 11, key: 'photthabbayatana', pali: 'Phoṭṭhabbāyatana', name: 'ဖောဋ္ဌဗ္ဗာယတန', group: 'ayatana-external', icon: 'fa-hand-back-fist',
              desc: 'အတွေ့အာရုံ — ကာယာယတန၏ ဆိုင်ရာ အာယတန — ပထဝီ/တေဇော/ဝါယော မဟာဘုတ် (၃) ပါးနှင့် တူညီသည်။',
              example: 'ရူပသင်္ဂဟတွင် ဖော်ပြခဲ့သကဲ့သို့ သီးခြား ရုပ်သစ် မဟုတ်ဘဲ မဟာဘုတ် (၃) ပါးကိုပင် တိုက်ရိုက် ရည်ညွှန်းသည်။' },
            { id: 12, key: 'dhammayatana', pali: 'Dhammāyatana', name: 'ဓမ္မာယတန', group: 'ayatana-external', icon: 'fa-scroll',
              desc: 'စေတသိက် (၅၂)၊ ရုပ်သိမ်မွေ့ (၁၆)၊ နိဗ္ဗာန် — မနာယတန (စိတ်) ကသာ သိနိုင်သော အာရုံအားလုံး ခြုံငုံ။',
              example: 'ဓမ္မာရမ္မဏ (Ārammaṇa-saṅgaha တွင် ဖော်ပြခဲ့သော) နှင့် အနက်တူသည်။' },

            // Dhatu: pasada (5) — sky
            { id: 13, key: 'cakkhudhatu', pali: 'Cakkhu-dhātu', name: 'စက္ခုဓာတု', group: 'dhatu-pasada', icon: 'fa-eye',
              desc: 'စက္ခာယတနနှင့် အနက်တူ — "ဓာတု" ရှုထောင့်မှ ခေါ်ဝေါ်ခြင်း (မိမိသဘောကို မိမိ ဆောင်ထားသော အရာ ဟူသော အနက်)။',
              example: 'အာယတန/ဓာတု နှစ်မျိုးစလုံးသည် ရုပ်တစ်ပါးတည်းကိုပင် ကွဲပြားသော ရှုထောင့်ဖြင့် ခေါ်ဝေါ်ခြင်း ဖြစ်သည်။' },
            { id: 14, key: 'sotadhatu', pali: 'Sota-dhātu', name: 'သောတဓာတု', group: 'dhatu-pasada', icon: 'fa-ear-listen',
              desc: 'သောတာယတနနှင့် အနက်တူ။',
              example: 'နား၏ ပသာဒရုပ် တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 15, key: 'ghanadhatu', pali: 'Ghāna-dhātu', name: 'ဃာနဓာတု', group: 'dhatu-pasada', icon: 'fa-atom',
              desc: 'ဃာနာယတနနှင့် အနက်တူ။',
              example: 'နှာခေါင်း၏ ပသာဒရုပ် တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 16, key: 'jivhadhatu', pali: 'Jivhā-dhātu', name: 'ဇိဝှါဓာတု', group: 'dhatu-pasada', icon: 'fa-droplet',
              desc: 'ဇိဝှါယတနနှင့် အနက်တူ။',
              example: 'လျှာ၏ ပသာဒရုပ် တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 17, key: 'kayadhatu', pali: 'Kāya-dhātu', name: 'ကာယဓာတု', group: 'dhatu-pasada', icon: 'fa-hand',
              desc: 'ကာယာယတနနှင့် အနက်တူ။',
              example: 'ကိုယ်ခန္ဓာ၏ ပသာဒရုပ် တစ်ပါးတည်း ဖြစ်သည်။' },

            // Dhatu: visaya (5) — amber
            { id: 18, key: 'rupadhatu', pali: 'Rūpa-dhātu', name: 'ရူပဓာတု', group: 'dhatu-visaya', icon: 'fa-palette',
              desc: 'ရူပါယတနနှင့် အနက်တူ။',
              example: 'အဆင်းအာရုံ တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 19, key: 'saddadhatu', pali: 'Sadda-dhātu', name: 'သဒ္ဒဓာတု', group: 'dhatu-visaya', icon: 'fa-volume-high',
              desc: 'သဒ္ဒါယတနနှင့် အနက်တူ။',
              example: 'အသံအာရုံ တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 20, key: 'gandhadhatu', pali: 'Gandha-dhātu', name: 'ဂန္ဓဓာတု', group: 'dhatu-visaya', icon: 'fa-wind',
              desc: 'ဂန္ဓာယတနနှင့် အနက်တူ။',
              example: 'အနံ့အာရုံ တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 21, key: 'rasadhatu', pali: 'Rasa-dhātu', name: 'ရသဓာတု', group: 'dhatu-visaya', icon: 'fa-utensils',
              desc: 'ရသာယတနနှင့် အနက်တူ။',
              example: 'အရသာအာရုံ တစ်ပါးတည်း ဖြစ်သည်။' },
            { id: 22, key: 'photthabbadhatu', pali: 'Phoṭṭhabba-dhātu', name: 'ဖောဋ္ဌဗ္ဗဓာတု', group: 'dhatu-visaya', icon: 'fa-hand-back-fist',
              desc: 'ဖောဋ္ဌဗ္ဗာယတနနှင့် အနက်တူ။',
              example: 'အတွေ့အာရုံ (မဟာဘုတ် ၃ ပါး) တစ်ပါးတည်း ဖြစ်သည်။' },

            // Dhatu: vinnana (5) — emerald
            { id: 23, key: 'cakkhuvinnanadhatu', pali: 'Cakkhuviññāṇa-dhātu', name: 'စက္ခုဝိညာဏဓာတု', group: 'dhatu-vinnana', icon: 'fa-eye',
              desc: 'မြင်ခြင်း ဆောင်ရွက်သော ဝိညာဉ်စိတ် (၂) ပါး — ကုသိုလ်ဝိပါက်/အကုသိုလ်ဝိပါက်။',
              example: 'ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးအနက် စက္ခုဝိညာဉ် (၂) ပါးတည်း ဖြစ်သည်။' },
            { id: 24, key: 'sotavinnanadhatu', pali: 'Sotaviññāṇa-dhātu', name: 'သောတဝိညာဏဓာတု', group: 'dhatu-vinnana', icon: 'fa-ear-listen',
              desc: 'ကြားခြင်း ဆောင်ရွက်သော ဝိညာဉ်စိတ် (၂) ပါး။',
              example: 'ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးအနက် သောတဝိညာဉ် (၂) ပါးတည်း ဖြစ်သည်။' },
            { id: 25, key: 'ghanavinnanadhatu', pali: 'Ghānaviññāṇa-dhātu', name: 'ဃာနဝိညာဏဓာတု', group: 'dhatu-vinnana', icon: 'fa-atom',
              desc: 'နံခြင်း ဆောင်ရွက်သော ဝိညာဉ်စိတ် (၂) ပါး။',
              example: 'ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးအနက် ဃာနဝိညာဉ် (၂) ပါးတည်း ဖြစ်သည်။' },
            { id: 26, key: 'jivhavinnanadhatu', pali: 'Jivhāviññāṇa-dhātu', name: 'ဇိဝှါဝိညာဏဓာတု', group: 'dhatu-vinnana', icon: 'fa-droplet',
              desc: 'မြည်းစမ်းခြင်း ဆောင်ရွက်သော ဝိညာဉ်စိတ် (၂) ပါး။',
              example: 'ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးအနက် ဇိဝှါဝိညာဉ် (၂) ပါးတည်း ဖြစ်သည်။' },
            { id: 27, key: 'kayavinnanadhatu', pali: 'Kāyaviññāṇa-dhātu', name: 'ကာယဝိညာဏဓာတု', group: 'dhatu-vinnana', icon: 'fa-hand',
              desc: 'တွေ့ထိခြင်း ဆောင်ရွက်သော ဝိညာဉ်စိတ် (၂) ပါး။',
              example: 'ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးအနက် ကာယဝိညာဉ် (၂) ပါးတည်း ဖြစ်သည်။' },

            // Dhatu: mano-group (3) — rose
            { id: 28, key: 'manodhatu', pali: 'Mano-dhātu', name: 'မနောဓာတု', group: 'dhatu-mano', icon: 'fa-brain',
              desc: 'ပဉ္စဒွါရာဝဇ္ဇန်း (၁) + သမ္ပဋိစ္ဆန် (၂) — စုစုပေါင်း (၃) ပါး။',
              example: 'ဝီထိစိတ်တွင် ဒွိပဉ္စဝိညာဉ်နှင့် နီးစပ်စွာ ဆက်စပ်နေသော စိတ် (၃) ပါး တစ်စုတည်း ဖြစ်သည်။' },
            { id: 29, key: 'manovinnanadhatu', pali: 'Manoviññāṇa-dhātu', name: 'မနောဝိညာဏဓာတု', group: 'dhatu-mano', icon: 'fa-brain',
              desc: 'စိတ် (၈၉) ပါးအနက် မနောဓာတု (၃) ပါးနှင့် ဒွိပဉ္စဝိညာဉ် (၁၀) ပါးမှလွဲ၍ ကျန် (၇၆) ပါးလုံး။',
              example: 'ဇောနစိတ်၊ သန္တီရဏ၊ ဝုဋ္ဌပ္ပန်၊ တဒါရမ္မဏ အစရှိသည့် ဝီထိစိတ်အများစု ပါဝင်သည်။' },
            { id: 30, key: 'dhammadhatu', pali: 'Dhamma-dhātu', name: 'ဓမ္မဓာတု', group: 'dhatu-mano', icon: 'fa-scroll',
              desc: 'ဓမ္မာယတနနှင့် အနက်တူ — စေတသိက် (၅၂)၊ ရုပ်သိမ်မွေ့ (၁၆)၊ နိဗ္ဗာန်။',
              example: 'စိတ်မှလွဲ၍ ကျန်နာမ်ရုပ်တရားများ (မနောဝိညာဏဓာတုမှလွဲ၍) အားလုံး ပါဝင်သည်။' },

            // Sacca (4) — mixed colors
            { id: 31, key: 'dukkhasacca', pali: 'Dukkha-sacca', name: 'ဒုက္ခသစ္စာ', group: 'sacca', icon: 'fa-triangle-exclamation',
              desc: 'ဆင်းရဲမှု အမှန်တရား — ဥပါဒါနက္ခန္ဓာ (၅) ပါးတိုင်းသည် ဒုက္ခ ဖြစ်သည်။',
              example: 'ပဋိစ္စသမုပ္ပါဒ် နိဒါန်း (၁၂) ပါးတွင် ဇာတိ၊ ဇရာမရဏ အပါအဝင် ခန္ဓာ (၅) ပါးလုံးသည် ဒုက္ခသစ္စာ ဖြစ်သည်။' },
            { id: 32, key: 'samudayasacca', pali: 'Samudaya-sacca', name: 'သမုဒယသစ္စာ', group: 'sacca', icon: 'fa-fire',
              desc: 'ဒုက္ခ၏ အကြောင်း အမှန်တရား — တဏှာ။',
              example: 'ပဋိစ္စသမုပ္ပါဒ်တွင် "တဏှာ" နိဒါန်းသည် ဤသမုဒယသစ္စာကို တိုက်ရိုက် ကိုယ်စားပြုသည်။' },
            { id: 33, key: 'nirodhasacca', pali: 'Nirodha-sacca', name: 'နိရောဓသစ္စာ', group: 'sacca', icon: 'fa-om',
              desc: 'ဒုက္ခ ချုပ်ငြိမ်းရာ အမှန်တရား — နိဗ္ဗာန်။',
              example: 'အဝိဇ္ဇာ/တဏှာ လုံးဝ ချုပ်ငြိမ်းသည့်အခါ ဤနိရောဓသစ္စာသို့ ရောက်ရှိသည်။' },
            { id: 34, key: 'maggasacca', pali: 'Magga-sacca', name: 'မဂ္ဂသစ္စာ', group: 'sacca', icon: 'fa-route',
              desc: 'နိရောဓသို့ ဦးတည်စေသော လမ်းစဉ် အမှန်တရား — အရိယမဂ္ဂင် (၈) ပါး။',
              example: 'ဗောဓိပက္ခိယဓမ္မာ၏ မဂ္ဂင် (၈) ပါးသည် ဤမဂ္ဂသစ္စာကို တိုက်ရိုက် ကိုယ်စားပြုသည်။' }
        ];

