import re
import json

existing_terms_js = """
            { term: 'Adosa (အဒေါသ)', meaning: 'မကြမ်းတမ်းခြင်း၊ မေတ္တာထားခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Ahetuka (အဟေတုက)', meaning: 'ဟေတု (လောဘ၊ ဒေါသ စသည့် အမြစ်) မပါဝင်သော စိတ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Akusala (အကုသလ)', meaning: 'အပြစ်ရှိ၍ ဆင်းရဲသောအကျိုးကို ပေးတတ်သော သဘော (အကုသိုလ်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }, { name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Alobha (အလောဘ)', meaning: 'မလိုချင်ခြင်း၊ မတပ်မက်ခြင်း၊ စွန့်လွှတ်ခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Amoha (အမောဟ)', meaning: 'အမှန်အတိုင်း သိမြင်ခြင်း (ပညာ)' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Asaṅkhārika (အသင်္ခါရိက)', meaning: 'တိုက်တွန်းမှု မပါဘဲ မိမိအလိုအလျောက် ထက်မြက်စွာ ဖြစ်ပေါ်သော စိတ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Avijjā (အဝိဇ္ဇာ)', meaning: 'သစ္စာလေးပါးကို မသိခြင်း (မောဟ)' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }, { name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Bala (ဗလ)', meaning: 'ဆန့်ကျင်ဘက်တရားတို့ကို မတုန်လှုပ်စေသော အစွမ်းခွန်အား (သဒ္ဓါ၊ ဝီရိယ၊ သတိ၊ သမာဓိ၊ ပညာ)' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Bhavaṅga (ဘဝင်)', meaning: 'ဘဝ၏ အင်္ဂါ၊ ဘဝကို ဆက်စပ်ပေးသော၊ ဝီထိစိတ် မဖြစ်ပေါ်ချိန်တွင် ဖြစ်ပေါ်နေသော စိတ်' , links: [{ name: 'ဝီထိမုတ်ပိုင်း (Vīthimutta)', url: 'vithimutta_sangaha.html' }] },
            { term: 'Bhaṅga (ဘင်)', meaning: 'ချုပ်ပျောက်ခြင်း ခဏ' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Bhūmi (ဘူမိ / ဘုံ)', meaning: 'သတ္တဝါတို့ ဖြစ်တည်ရာ အရပ်၊ နေရာ (ဥပမာ - ကာမဘုံ၊ ရူပဘုံ၊ အရူပဘုံ)' , links: [{ name: 'ဝီထိမုတ်ပိုင်း (Vīthimutta)', url: 'vithimutta_sangaha.html' }] },
            { term: 'Bojjhaṅga (ဗောဇ္ဈင်္ဂ / ဗောဇ္ဈင်)', meaning: 'သစ္စာလေးပါးကို သိရန် အထောက်အကူပြုသော အင်္ဂါ' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Cetasika (စေတသိက)', meaning: 'စိတ်နှင့် ယှဉ်တွဲ၍ ဖြစ်ပေါ်သော၊ စိတ်ကို ခြယ်လှယ်တတ်သော သဘောတရားများ (စေတသိက်)' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Citta (စိတ္တ)', meaning: 'အာရုံကို သိတတ်သော သဘော (စိတ်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Cuti (စုတိ)', meaning: 'ဘဝတစ်ခု၏ နောက်ဆုံး ပြတ်စဲသွားသော စိတ်' , links: [{ name: 'ဝီထိမုတ်ပိုင်း (Vīthimutta)', url: 'vithimutta_sangaha.html' }] },
            { term: 'Dhātu (ဓာတု / ဓာတ်)', meaning: 'သတ္တဝါ၊ ဇီဝ မဟုတ်ဘဲ မိမိသဘောကို ဆောင်သော တရား (ဥပမာ - ပထဝီဓာတ်၊ စက္ခုဓာတ် စသည်)' , links: [{ name: 'သဗ္ဗသင်္ဂဟ (Sabba Saṅgaha)', url: 'sabba_sangaha.html' }] },
            { term: 'Diṭṭhi (ဒိဋ္ဌိ)', meaning: 'မှားယွင်းစွာ ယူဆခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Dosa (ဒေါသ)', meaning: 'ကြမ်းတမ်းခြင်း၊ အမျက်ထွက်ခြင်း၊ မကျေနပ်ခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Dvāra (ဒွါရ)', meaning: 'စိတ်ဖြစ်ပေါ်ရန် ဝင်ပေါက်/ထွက်ပေါက် (တံခါး ၆ ပေါက်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Hetu (ဟေတု / ဟိတ်)', meaning: 'အမြစ်သဖွယ်ဖြစ်သော အကြောင်းတရား (ဥပမာ - လောဘ၊ ဒေါသ၊ မောဟ၊ အလောဘ၊ အဒေါသ၊ အမောဟ)' , links: [{ name: 'ပစ္စည်းပိုင်း (Paccaya)', url: 'paccaya_sangaha.html' }] },
            { term: 'Hiri (ဟိရီ)', meaning: 'ဒုစရိုက်ပြုရမည်ကို ရှက်ခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Iddhipāda (ဣဒ္ဓိပါဒ / ဣဒ္ဓိပါဒ်)', meaning: 'ပြီးပြည့်စုံခြင်း၏ အခြေခံ (ဆန္ဒ၊ ဝီရိယ၊ စိတ္တ၊ ဝီမံသ)' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Indriya (ဣန္ဒြိယ / ဣန္ဒြေ)', meaning: 'မိမိဆိုင်ရာ ကိစ္စ၌ အစိုးရသော၊ လွှမ်းမိုးနိုင်သော သဘော (ဥပမာ - စက္ခုန္ဒြေ၊ သဒ္ဓိန္ဒြေ စသည်)' , links: [{ name: 'သဗ္ဗသင်္ဂဟ (Sabba Saṅgaha)', url: 'sabba_sangaha.html' }] },
            { term: 'Jarā (ဇရာ)', meaning: 'အိုမင်း ရင့်ရော်ခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Javana (ဇောန / ဇော)', meaning: 'အာရုံ၏ အရသာကို လျင်မြန်စွာ ခံစားသော၊ ကံမြောက်စေသော စိတ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Jhāna (ဈာန / ဈာန်)', meaning: 'အာရုံကို စူးစိုက်စွာ ရှုတတ်သော၊ ဆန့်ကျင်ဘက် နီဝရဏတရားများကို လောင်ကျွမ်းစေတတ်သော သဘော' , links: [{ name: 'ကမ္မဋ္ဌာန်းပိုင်း (Kammaṭṭhāna)', url: 'kammatthana_sangaha.html' }] },
            { term: 'Jāti (ဇာတိ)', meaning: 'ပဋိသန္ဓေတည်နေခြင်း၊ ပထမဆုံး ဖြစ်ပေါ်လာခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Kamma (ကမ္မ / ကံ)', meaning: 'ပြုလုပ်ခြင်း၊ စီမံခြင်း (ကိုယ်၊ နှုတ်၊ စိတ်ဖြင့် ပြုလုပ်သော အကြောင်းတရား)' , links: [{ name: 'ပစ္စည်းပိုင်း (Paccaya)', url: 'paccaya_sangaha.html' }] },
            { term: 'Kammaṭṭhāna (ကမ္မဋ္ဌာန)', meaning: 'ဘာဝနာအလုပ်၏ တည်ရာ အာရုံ' , links: [{ name: 'ကမ္မဋ္ဌာန်းပိုင်း (Kammaṭṭhāna)', url: 'kammatthana_sangaha.html' }] },
            { term: 'Khandha (ခန္ဓာ)', meaning: 'အစုအဝေး (ဥပမာ - ရူပက္ခန္ဓာ၊ ဝေဒနာက္ခန္ဓာ စသည်)' , links: [{ name: 'သဗ္ဗသင်္ဂဟ (Sabba Saṅgaha)', url: 'sabba_sangaha.html' }] },
            { term: 'Kicca (ကိစ္စ)', meaning: 'စိတ်၏ လုပ်ငန်းဆောင်တာ (၁၄ မျိုး ရှိသည်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Kilesā (ကိလေသာ)', meaning: 'စိတ်ကို ပူလောင် ညစ်နွမ်းစေတတ်သော သဘော' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Kiriya / Kriyā (ကြိယာ)', meaning: 'အကျိုး မပေးတော့သော၊ ပြုကာမတ္တမျှသာဖြစ်သော သဘော (ရဟန္တာများ၏ စိတ်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Kukkucca (ကုက္ကုစ္စ)', meaning: 'ပြုခဲ့မိသော အမှား၊ မပြုခဲ့မိသော အကောင်းများအတွက် နောင်တရ ပူပန်ခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Kusala (ကုသလ)', meaning: 'အပြစ်ကင်း၍ ကောင်းသောအကျိုးကို ပေးတတ်သော သဘော (ကုသိုလ်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Lobha (လောဘ)', meaning: 'လိုချင်တပ်မက်ခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Magga (မဂ္ဂ / မဂ်)', meaning: 'နိဗ္ဗာန်သို့ သွားရာလမ်း၊ ကိလေသာများကို ပယ်သတ်တတ်သော သဘော' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Mahābhūta (မဟာဘူတ)', meaning: 'ကြီးမား ထင်ရှားသော ရုပ်တရား (ပထဝီ၊ အာပေါ၊ တေဇော၊ ဝါယော)' , links: [{ name: 'ရုပ်ပိုင်း (Rūpa)', url: 'rupa_sangaha.html' }] },
            { term: 'Maraṇa (မရဏ)', meaning: 'သေဆုံးခြင်း၊ ပျက်စီးခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Moha (မောဟ)', meaning: 'တွေဝေခြင်း၊ အမှန်ကို မသိခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Māna (မာန)', meaning: 'ထောင်လွှားခြင်း၊ မိမိကိုယ်ကို အထင်ကြီးခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Nibbāna (နိဗ္ဗာန)', meaning: 'တဏှာမှ ကင်းလွတ်ရာ၊ ဒုက္ခငြိမ်းရာ (နိဗ္ဗာန်)' },
            { term: 'Nimitta (နိမိတ္တ / နိမိတ်)', meaning: 'အာရုံ၏ အမှတ်အသား (ဥပမာ - ပရိကမ္မနိမိတ်၊ ဥဂ္ဂဟနိမိတ်၊ ပဋိဘာဂနိမိတ်)' , links: [{ name: 'ကမ္မဋ္ဌာန်းပိုင်း (Kammaṭṭhāna)', url: 'kammatthana_sangaha.html' }] },
            { term: 'Nāmarūpa (နာမရူပ / နာမ်ရုပ်)', meaning: 'စိတ်၊ စေတသိက် (နာမ်) နှင့် ဖောက်ပြန်တတ်သော သဘော (ရုပ်)' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Ottappa (ဩတ္တပ္ပ)', meaning: 'ဒုစရိုက်ပြုရမည်ကို ကြောက်ခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Paccaya (ပစ္စယ)', meaning: 'တစ်ခုက တစ်ခုကို ထောက်ပံ့ ကျေးဇူးပြုတတ်သော အခြေအနေ' , links: [{ name: 'ပစ္စည်းပိုင်း (Paccaya)', url: 'paccaya_sangaha.html' }] },
            { term: 'Paramattha (ပရမတ္ထ / ပရမတ်)', meaning: 'ဖောက်ပြန်လွဲမှားခြင်း မရှိသော၊ အမှန်တကယ် ရှိသော တရား (စိတ်၊ စေတသိက်၊ ရုပ်၊ နိဗ္ဗာန်)' },
            { term: 'Paññatti (ပညတ္တိ / ပညတ်)', meaning: 'အမှန်တကယ် မရှိသော်လည်း ခေါ်ဝေါ်သမုတ်ထားသော အမည်နာမ သို့မဟုတ် အရာဝတ္ထု' },
            { term: 'Paṭiccasamuppāda (ပဋိစ္စသမုပ္ပါဒ)', meaning: 'အကြောင်းတရားများအပေါ် အမှီသဟဲပြု၍ အကျိုးတရားများ ဆက်စပ်ဖြစ်ပေါ်လာခြင်း သဘော' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Paṭisandhi (ပဋိသန္ဓေ)', meaning: 'ဘဝဟောင်းနှင့် ဘဝသစ်ကို ဆက်စပ်ပေးသော၊ ဘဝသစ်၏ ပထမဆုံး စိတ်' , links: [{ name: 'ဝီထိမုတ်ပိုင်း (Vīthimutta)', url: 'vithimutta_sangaha.html' }] },
            { term: 'Paṭṭhāna (ပဋ္ဌာန / ပဋ္ဌာန်း)', meaning: 'အကြောင်းအကျိုး ဆက်စပ်မှုတို့ကို အထူး၊ အပြားအားဖြင့် ပြဆိုထားသော ကျမ်း (ပစ္စည်း ၂၄ ပါး)' , links: [{ name: 'ပစ္စည်းပိုင်း (Paccaya)', url: 'paccaya_sangaha.html' }] },
            { term: 'Phala (ဖလ / ဖိုလ်)', meaning: 'မဂ်၏ အကျိုးဆက်အဖြစ် ဖြစ်ပေါ်လာသော သဘော' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Phassa (ဖဿ)', meaning: 'အာရုံနှင့် ဒွါရ တွေ့ဆုံထိခိုက်ခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Rūpa (ရူပ)', meaning: 'ဖောက်ပြန်တတ်သော သဘော (ရုပ်တရား)' , links: [{ name: 'ရုပ်ပိုင်း (Rūpa)', url: 'rupa_sangaha.html' }] },
            { term: 'Sacca (သစ္စ / သစ္စာ)', meaning: 'ဖောက်ပြန်လွဲမှားမှု မရှိသော အမှန်တရား (ဥပမာ - ဒုက္ခသစ္စာ၊ သမုဒယသစ္စာ စသည်)' , links: [{ name: 'သဗ္ဗသင်္ဂဟ (Sabba Saṅgaha)', url: 'sabba_sangaha.html' }] },
            { term: 'Saddhā (သဒ္ဓါ)', meaning: 'ယုံကြည်သင့်သည်ကို ယုံကြည်ခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Sahetuka (သဟေတုက)', meaning: 'ဟေတု ပါဝင်သော စိတ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Samatha (သမထ)', meaning: 'စိတ်ကို ငြိမ်းအေး တည်ငြိမ်စေသော အကျင့်' , links: [{ name: 'ကမ္မဋ္ဌာန်းပိုင်း (Kammaṭṭhāna)', url: 'kammatthana_sangaha.html' }] },
            { term: 'Sammappadhāna (သမ္မပ္ပဓာန)', meaning: 'ကောင်းစွာ အားထုတ်ခြင်း (ဝီရိယ ၄ မျိုး)' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Sampayutta (သမ္ပယုတ္တ)', meaning: 'ယှဉ်တွဲခြင်း၊ အတူတကွ ဖြစ်ပေါ်ခြင်း (ဥပမာ - ဉာဏသမ္ပယုတ်)' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Sasaṅkhārika (သသင်္ခါရိက)', meaning: 'မိမိ/သူတစ်ပါး၏ တိုက်တွန်းမှုကြောင့် နှေးကွေးစွာ ဖြစ်ပေါ်သော စိတ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Sati (သတိ)', meaning: 'အာရုံကို မမေ့လျော့ခြင်း' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Satipaṭṭhāna (သတိပဋ္ဌာန / သတိပဋ္ဌာန်)', meaning: 'သတိကို စွဲမြဲစွာ တည်ထားခြင်း (ကာယ၊ ဝေဒနာ၊ စိတ္တ၊ ဓမ္မ)' , links: [{ name: 'ဗောဓိပက္ခိယ (Bodhipakkhiya)', url: 'bodhipakkhiya_dhamma.html' }] },
            { term: 'Saḷāyatana (သဠာယတန)', meaning: 'အာယတန ၆ ပါး (စက္ခု၊ သောတ၊ ဃာန၊ ဇိဝှာ၊ ကာယ၊ မန)' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Saṅkhāra (သင်္ခါရ)', meaning: 'အကြောင်းတရားတို့က ပြုပြင်စီရင်ထားသော တရား၊ ပြုပြင်တတ်သော စေတနာ' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Taṇhā (တဏှာ)', meaning: 'အာရုံကို တပ်မက်ခြင်း၊ လိုချင်ခြင်း (လောဘ)' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }, { name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Thīna-Middha (ထိန-မိဒ္ဓ)', meaning: 'စိတ်နှင့် စေတသိက်တို့၏ ထိုင်းမှိုင်းခြင်း၊ လေးလံခြင်း' },
            { term: 'Uddhacca (ဥဒ္ဓစ္စ)', meaning: 'စိတ် ပျံ့လွင့်ခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Uppāda (ဥပါဒ်)', meaning: 'စတင်ဖြစ်ပေါ်ခြင်း ခဏ' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Upādāna (ဥပါဒါန / ဥပါဒါန်)', meaning: 'အာရုံကို ပြင်းစွာ စွဲလမ်းခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Upādārūpa (ဥပါဒါရူပ / ဥပါဒါရုပ်)', meaning: 'မဟာဘုတ် ၄ ပါးကို မှီ၍ ဖြစ်သော ရုပ် (၂၄ ပါး)' , links: [{ name: 'ရုပ်ပိုင်း (Rūpa)', url: 'rupa_sangaha.html' }] },
            { term: 'Vatthu (ဝတ္ထု)', meaning: 'စိတ် မှီရာ ရုပ်အခြေခံ (ဝတ္ထုရုပ် ၆ ပါး)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Vedanā (ဝေဒနာ)', meaning: 'အာရုံ၏ အရသာကို ခံစားခြင်း' , links: [{ name: 'ပဋိစ္စသမုပ္ပါဒ် (Paṭiccasamuppāda)', url: 'paticcasamuppada.html' }] },
            { term: 'Vicikicchā (ဝိစိကိစ္ဆာ)', meaning: 'ယုံမှား သံသယဖြစ်ခြင်း' , links: [{ name: 'ကိလေသာပိုင်း (Kilesa)', url: 'kilesa_sangaha.html' }] },
            { term: 'Vipassanā (ဝိပဿနာ)', meaning: 'ရုပ်နာမ်တို့၏ အနိစ္စ၊ ဒုက္ခ၊ အနတ္တ သဘောကို အထူး သိမြင်အောင် ရှုပွားသော အကျင့်' , links: [{ name: 'ကမ္မဋ္ဌာန်းပိုင်း (Kammaṭṭhāna)', url: 'kammatthana_sangaha.html' }] },
            { term: 'Vippayutta (ဝိပ္ပယုတ္တ)', meaning: 'မယှဉ်တွဲခြင်း၊ ကင်းကွာခြင်း (ဥပမာ - ဉာဏဝိပ္ပယုတ်)' , links: [{ name: 'စေတသိက်ပိုင်း (Cetasika)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Vipāka (ဝိပါက)', meaning: 'ကံ၏ အကျိုးဆက်အဖြစ် ဖြစ်ပေါ်လာသော သဘော (ဝိပါက်)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Vīthi (ဝီထိ)', class: 'text-sky-700 dark:text-sky-300', meaning: 'အာရုံကို သိရှိရန် အစဉ်အတိုင်း ဖြစ်ပေါ်သော စိတ်အစဉ်' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Ārammaṇa (အာရမ္မဏ)', meaning: 'စိတ်၏ မှီတွယ်ရာ/သိစရာ (အာရုံ ၆ ပါး)' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] },
            { term: 'Āyatana (အာယတန)', meaning: 'စိတ်နှင့် စေတသိက်တို့ ဖြစ်ပေါ်ကျယ်ပြန့်ရာ အကြောင်း (ဥပမာ - စက္ခာယတန၊ ရူပါယတန စသည်)' , links: [{ name: 'သဗ္ဗသင်္ဂဟ (Sabba Saṅgaha)', url: 'sabba_sangaha.html' }] },
            { term: 'Ṭhiti (ဌီ)', meaning: 'တည်နေခြင်း ခဏ' , links: [{ name: 'စိတ်ပိုင်း (Citta)', url: 'citta_cetasikas_visual_guide.html' }] }
"""
